begin;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id varchar(64) not null unique,
  name text,
  email varchar(320),
  login_method varchar(64),
  role varchar(16) not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.dashboard_report_schedules (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null,
  owner_open_id varchar(64) not null,
  company_id uuid not null,
  name varchar(120) not null,
  recipient_email varchar(320) not null,
  cc_emails varchar(2000) not null default '',
  cron_expression varchar(64) not null,
  frequency varchar(24) not null,
  format varchar(8) not null,
  modules jsonb not null,
  date_range jsonb not null,
  schedule_cron_task_uid varchar(65),
  is_active boolean not null default true,
  last_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_open_id varchar(64) not null,
  actor_name varchar(120),
  company_id uuid not null,
  action varchar(100) not null,
  module varchar(50) not null,
  details text,
  created_at timestamptz not null default now()
);

create table if not exists public.webhook_deliveries (
  id bigint generated by default as identity primary key,
  delivery_id varchar(80) not null unique,
  company_id uuid not null,
  action varchar(100) not null,
  module varchar(50) not null,
  severity varchar(16) not null,
  status varchar(16) not null check (status in ('success', 'failed', 'retrying')),
  attempts integer not null default 0 check (attempts >= 0),
  response_code integer,
  error text,
  event_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schema_drift_monitors (
  id bigint generated by default as identity primary key,
  monitor_key varchar(80) not null unique,
  cron_expression varchar(64) not null,
  schedule_cron_task_uid varchar(65),
  is_active boolean not null default true,
  last_checked_at timestamptz,
  last_status varchar(16),
  last_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schema_drift_runs (
  id bigint generated by default as identity primary key,
  monitor_id bigint not null references public.schema_drift_monitors(id) on delete cascade,
  status varchar(16) not null check (status in ('healthy', 'drift', 'error')),
  referenced_table_count integer not null default 0 check (referenced_table_count >= 0),
  deployed_table_count integer not null default 0 check (deployed_table_count >= 0),
  missing_tables jsonb not null default '[]'::jsonb,
  tenant_table_issues jsonb not null default '[]'::jsonb,
  notification_delivered boolean not null default false,
  error text,
  checked_at timestamptz not null default now()
);

create table if not exists public.tra_z_report_archive_schedules (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null,
  owner_open_id varchar(64) not null,
  company_id uuid not null,
  branch_id varchar(64) not null default 'MAIN',
  cron_expression varchar(64) not null,
  schedule_cron_task_uid varchar(65),
  is_active boolean not null default true,
  last_run_at timestamptz,
  last_run_status varchar(24),
  last_archive_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tra_z_report_archives (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  branch_id varchar(64) not null default 'MAIN',
  business_date varchar(32) not null,
  z_report_id bigint,
  z_number varchar(64),
  status varchar(24) not null,
  storage_key varchar(500),
  storage_url varchar(500),
  content_type varchar(120) not null default 'application/json',
  archive_bytes integer not null default 0 check (archive_bytes >= 0),
  summary jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists public.tra_gateway_alert_settings (
  id bigint generated by default as identity primary key,
  company_id uuid not null unique,
  enabled boolean not null default false,
  timeout_threshold_ms integer not null default 1500 check (timeout_threshold_ms >= 0),
  cooldown_minutes integer not null default 30 check (cooldown_minutes >= 0),
  last_alert_at timestamptz,
  last_delivery_status varchar(24),
  last_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tra_gateway_alert_events (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  branch_id varchar(64),
  provider_status varchar(24) not null,
  latency_ms integer not null check (latency_ms >= 0),
  threshold_ms integer not null check (threshold_ms >= 0),
  delivery_status varchar(24) not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tra_vat_anomaly_settings (
  id bigint generated by default as identity primary key,
  company_id uuid not null unique,
  enabled boolean not null default true,
  threshold_percent integer not null default 50 check (threshold_percent >= 0),
  cooldown_minutes integer not null default 1440 check (cooldown_minutes >= 0),
  cron_expression varchar(64) not null default '0 0 6 * * *',
  schedule_cron_task_uid varchar(65),
  last_evaluated_at timestamptz,
  last_alert_at timestamptz,
  last_delivery_status varchar(24),
  last_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tra_vat_anomaly_events (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  branch_id varchar(64),
  period varchar(32) not null,
  current_vat varchar(40) not null,
  historical_average_vat varchar(40) not null,
  variance_percent varchar(40) not null,
  threshold_percent integer not null check (threshold_percent >= 0),
  status varchar(24) not null,
  delivery_status varchar(24) not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bank_market_rates (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  bank_name varchar(160) not null,
  currency_pair varchar(32) not null default 'USD/TZS',
  buy_rate varchar(32) not null,
  sell_rate varchar(32) not null,
  lending_rate_annual varchar(32) not null,
  status varchar(32) not null default 'UNAVAILABLE',
  source varchar(160) not null default 'Bank of Tanzania (BOT) Feed',
  updated_at timestamptz not null default now()
);

create table if not exists public.dse_market_tickers (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  symbol varchar(32) not null,
  company_name varchar(160) not null,
  price_tzs varchar(32) not null,
  change_tzs varchar(32),
  change_percent varchar(32),
  volume integer,
  status varchar(32) not null default 'UNAVAILABLE',
  updated_at timestamptz not null default now()
);

create table if not exists public.market_provider_settings (
  id bigint generated by default as identity primary key,
  company_id uuid not null unique,
  bank_provider_url text,
  bank_provider_api_key text,
  dse_provider_url text,
  dse_provider_api_key text,
  cbk_provider_url text,
  cbk_provider_api_key text,
  bou_provider_url text,
  bou_provider_api_key text,
  bnr_provider_url text,
  bnr_provider_api_key text,
  slack_webhook_url text,
  outage_email_recipients text,
  alert_on_outage boolean not null default true,
  refresh_interval_seconds integer not null default 60 check (refresh_interval_seconds > 0),
  schedule_weekly_email boolean not null default false,
  latency_threshold_ms integer not null default 1500 check (latency_threshold_ms >= 0),
  alert_cooldown_minutes integer not null default 15 check (alert_cooldown_minutes >= 0),
  schedule_cron_task_uid varchar(65),
  last_alert_dispatched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_provider_uptime_logs (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  provider_type varchar(32) not null,
  status varchar(32) not null,
  latency_ms integer not null default 0 check (latency_ms >= 0),
  status_code integer,
  error_message text,
  checked_at timestamptz not null default now()
);

create table if not exists public.market_provider_incidents (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  provider_type varchar(32) not null,
  issue_summary varchar(255) not null,
  severity varchar(24) not null default 'OUTAGE',
  status varchar(24) not null default 'OPEN' check (status in ('OPEN', 'RESOLVED')),
  resolution_notes text,
  opened_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists dashboard_report_owner_open_id_idx on public.dashboard_report_schedules(owner_open_id);
create index if not exists dashboard_report_task_uid_idx on public.dashboard_report_schedules(schedule_cron_task_uid);
create index if not exists audit_logs_company_id_idx on public.audit_logs(company_id);
create index if not exists audit_logs_actor_open_id_idx on public.audit_logs(actor_open_id);
create index if not exists webhook_delivery_company_status_idx on public.webhook_deliveries(company_id, status);
create index if not exists webhook_delivery_created_at_idx on public.webhook_deliveries(created_at);
create index if not exists schema_drift_monitor_key_idx on public.schema_drift_monitors(monitor_key);
create index if not exists schema_drift_monitor_task_uid_idx on public.schema_drift_monitors(schedule_cron_task_uid);
create index if not exists schema_drift_runs_monitor_checked_at_idx on public.schema_drift_runs(monitor_id, checked_at);
create index if not exists schema_drift_runs_status_checked_at_idx on public.schema_drift_runs(status, checked_at);
create index if not exists tra_z_archive_schedule_owner_idx on public.tra_z_report_archive_schedules(owner_open_id);
create unique index if not exists tra_z_archive_schedule_company_branch_unique on public.tra_z_report_archive_schedules(company_id, branch_id);
create index if not exists tra_z_archive_schedule_task_uid_idx on public.tra_z_report_archive_schedules(schedule_cron_task_uid);
create unique index if not exists tra_z_archive_company_branch_date_unique on public.tra_z_report_archives(company_id, branch_id, business_date);
create index if not exists tra_z_archive_company_created_idx on public.tra_z_report_archives(company_id, created_at);
create index if not exists tra_gateway_alert_company_idx on public.tra_gateway_alert_settings(company_id);
create index if not exists tra_gateway_alert_event_company_created_idx on public.tra_gateway_alert_events(company_id, created_at);
create index if not exists tra_vat_anomaly_company_idx on public.tra_vat_anomaly_settings(company_id);
create index if not exists tra_vat_anomaly_task_uid_idx on public.tra_vat_anomaly_settings(schedule_cron_task_uid);
create index if not exists tra_vat_anomaly_event_company_created_idx on public.tra_vat_anomaly_events(company_id, created_at);
create index if not exists bank_market_rates_company_bank_idx on public.bank_market_rates(company_id, bank_name);
create index if not exists bank_market_rates_bank_name_idx on public.bank_market_rates(bank_name);
create index if not exists dse_market_tickers_company_symbol_idx on public.dse_market_tickers(company_id, symbol);
create index if not exists dse_market_tickers_symbol_idx on public.dse_market_tickers(symbol);
create index if not exists market_provider_settings_company_idx on public.market_provider_settings(company_id);
create index if not exists market_uptime_company_checked_idx on public.market_provider_uptime_logs(company_id, checked_at);
create index if not exists market_incident_company_status_idx on public.market_provider_incidents(company_id, status);

-- Tenant-scoped tables are protected by the existing current_company_id() UUID context.
do $rls$
declare
  table_name text;
begin
  foreach table_name in array array[
    'dashboard_report_schedules', 'audit_logs', 'webhook_deliveries',
    'tra_z_report_archive_schedules', 'tra_z_report_archives',
    'tra_gateway_alert_settings', 'tra_gateway_alert_events',
    'tra_vat_anomaly_settings', 'tra_vat_anomaly_events',
    'bank_market_rates', 'dse_market_tickers', 'market_provider_settings',
    'market_provider_uptime_logs', 'market_provider_incidents'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = table_name and policyname = table_name || '_tenant_isolation'
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (company_id = public.current_company_id()) with check (company_id = public.current_company_id())',
        table_name || '_tenant_isolation', table_name
      );
    end if;
  end loop;
end
$rls$;

-- Platform-level tables are RLS-enabled with no public policy; service-role/server paths retain access.
alter table public.users enable row level security;
alter table public.schema_drift_monitors enable row level security;
alter table public.schema_drift_runs enable row level security;

commit;
