-- Review-only plan generated from the live Supabase FK catalog and repository allowlist.
-- DO NOT run inside a transaction: CREATE INDEX CONCURRENTLY cannot run in a transaction block.
-- Execute one statement at a time after reviewing lock, storage, and workload impact.
-- No DDL was executed by this generator.

-- WAVE 1: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_customers_bank_customers_branch_id_fkey_fk_idx_d694d3e3" ON public."bank_customers" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_account_beneficiaries_bank_account_beneficiaries__a811f2c8" ON public."bank_account_beneficiaries" ("account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_account_beneficiaries_bank_account_beneficiaries__eac27028" ON public."bank_account_beneficiaries" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_agents_bank_agents_branch_id_fkey_fk_idx_8d03bd49" ON public."bank_agents" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_aml_alerts_bank_aml_alerts_customer_id_fkey_fk_id_54fc14be" ON public."bank_aml_alerts" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_aml_alerts_bank_aml_alerts_transaction_id_fkey_fk_0ede8cde" ON public."bank_aml_alerts" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_beneficial_owners_bank_beneficial_owners_company__de2f9eff" ON public."bank_beneficial_owners" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_beneficial_owners_bank_beneficial_owners_customer_9a500f36" ON public."bank_beneficial_owners" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_branches_bank_branches_institution_id_fkey_fk_idx_eeef0c85" ON public."bank_branches" ("institution_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_cash_movements_bank_cash_movements_branch_id_fkey_793786ae" ON public."bank_cash_movements" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_cash_movements_bank_cash_movements_teller_id_fkey_57875cda" ON public."bank_cash_movements" ("teller_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_cash_movements_bank_cash_movements_transaction_id_8dd028f7" ON public."bank_cash_movements" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_collateral_bank_collateral_application_id_fkey_fk_c0eefda5" ON public."bank_collateral" ("application_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_collateral_bank_collateral_company_id_fkey_fk_idx_424eec6f" ON public."bank_collateral" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_customer_documents_bank_customer_documents_custom_ab2d70e4" ON public."bank_customer_documents" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_group_members_bank_group_members_company_id_fkey__d6b1314b" ON public."bank_group_members" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_group_members_bank_group_members_customer_id_fkey_36018064" ON public."bank_group_members" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_groups_bank_groups_branch_id_fkey_fk_idx_becefb7b" ON public."bank_groups" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_guarantors_bank_guarantors_application_id_fkey_fk_64e464a9" ON public."bank_guarantors" ("application_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_guarantors_bank_guarantors_company_id_fkey_fk_idx_e3149403" ON public."bank_guarantors" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_guarantors_bank_guarantors_customer_id_fkey_fk_id_62d65391" ON public."bank_guarantors" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_journal_lines_bank_journal_lines_account_id_fkey__55c61c35" ON public."bank_journal_lines" ("account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_journal_lines_bank_journal_lines_batch_id_fkey_fk_e23ded91" ON public."bank_journal_lines" ("batch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_applications_bank_loan_applications_branch_i_0bf1df60" ON public."bank_loan_applications" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_applications_bank_loan_applications_customer_5f4b6b49" ON public."bank_loan_applications" ("customer_id");

-- WAVE 2: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_applications_bank_loan_applications_product__7ee821a3" ON public."bank_loan_applications" ("product_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_approvals_bank_loan_approvals_company_id_fke_4bb96bbb" ON public."bank_loan_approvals" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_repayments_bank_loan_repayments_account_id_f_5bcff4e0" ON public."bank_loan_repayments" ("account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_repayments_bank_loan_repayments_loan_id_fkey_ddec6688" ON public."bank_loan_repayments" ("loan_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_loan_repayments_bank_loan_repayments_transaction__7e46883d" ON public."bank_loan_repayments" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_notifications_bank_notifications_customer_id_fkey_5890ee57" ON public."bank_notifications" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_payment_instructions_bank_payment_instructions_de_a81ded5d" ON public."bank_payment_instructions" ("destination_account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_payment_instructions_bank_payment_instructions_so_6f732b8e" ON public."bank_payment_instructions" ("source_account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_reconciliations_bank_reconciliations_account_id_f_3c834d58" ON public."bank_reconciliations" ("account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_shares_bank_shares_company_id_fkey_fk_idx_9f4336db" ON public."bank_shares" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_shares_bank_shares_customer_id_fkey_fk_idx_e9d65eb7" ON public."bank_shares" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_shares_bank_shares_group_id_fkey_fk_idx_204523ad" ON public."bank_shares" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_shares_bank_shares_transaction_id_fkey_fk_idx_0ebfc7d0" ON public."bank_shares" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_tellers_bank_tellers_branch_id_fkey_fk_idx_6d533a6a" ON public."bank_tellers" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_wallets_bank_wallets_customer_id_fkey_fk_idx_0e90b27f" ON public."bank_wallets" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_accounts_fin_accounts_created_by_fkey_fk_idx_cd4c97ca" ON public."fin_accounts" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_accounts_fin_accounts_updated_by_fkey_fk_idx_870a1b64" ON public."fin_accounts" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_journal_lines_fin_journal_lines_created_by_fkey_fk_1ea9928d" ON public."fin_journal_lines" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_journal_lines_fin_journal_lines_updated_by_fkey_fk_8c63ad88" ON public."fin_journal_lines" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_journal_batches_fin_journal_batches_created_by_fke_40fd6af0" ON public."fin_journal_batches" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_journal_batches_fin_journal_batches_posted_by_fkey_938b7ee8" ON public."fin_journal_batches" ("posted_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_journal_batches_fin_journal_batches_reversal_compa_260df19a" ON public."fin_journal_batches" ("company_id", "reversal_of_batch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_journal_batches_fin_journal_batches_updated_by_fke_43a66d1d" ON public."fin_journal_batches" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_approval_requests_fin_approval_requests_created_by_7eb42c75" ON public."fin_approval_requests" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_approval_requests_fin_approval_requests_decided_by_2b59a592" ON public."fin_approval_requests" ("decided_by");

-- WAVE 3: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_approval_requests_fin_approval_requests_requested__879e343f" ON public."fin_approval_requests" ("requested_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_approval_requests_fin_approval_requests_updated_by_03f14c5b" ON public."fin_approval_requests" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_idempotency_keys_fin_idempotency_keys_created_by_f_ef2669d6" ON public."fin_idempotency_keys" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_idempotency_keys_fin_idempotency_keys_updated_by_f_1427119f" ON public."fin_idempotency_keys" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_periods_fin_periods_closed_by_fkey_fk_idx_3637fd38" ON public."fin_periods" ("closed_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_periods_fin_periods_created_by_fkey_fk_idx_49a3256b" ON public."fin_periods" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_periods_fin_periods_updated_by_fkey_fk_idx_23233c32" ON public."fin_periods" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_posting_links_fin_posting_links_created_by_fkey_fk_cf29cff6" ON public."fin_posting_links" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_reconciliation_batches_fin_reconciliation_batches__ed498e13" ON public."fin_reconciliation_batches" ("approved_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_reconciliation_batches_fin_reconciliation_batches__a4b3843a" ON public."fin_reconciliation_batches" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_reconciliation_batches_fin_reconciliation_batches__3a4b4e5d" ON public."fin_reconciliation_batches" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_reconciliation_items_fin_reconciliation_items_crea_c5cdd64b" ON public."fin_reconciliation_items" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_reconciliation_items_fin_reconciliation_items_reso_e7d2e2f1" ON public."fin_reconciliation_items" ("resolved_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fin_reconciliation_items_fin_reconciliation_items_upda_510f29df" ON public."fin_reconciliation_items" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_approval_limits_workforce_approval_limits_as_d998d89b" ON public."workforce_approval_limits" ("assigned_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_approval_limits_workforce_approval_limits_co_918a0e05" ON public."workforce_approval_limits" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_approval_limits_workforce_approval_limits_co_b6b535b9" ON public."workforce_approval_limits" ("company_id", "target_role_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_approval_limits_workforce_approval_limits_re_c49244bd" ON public."workforce_approval_limits" ("revoked_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_approval_limits_workforce_approval_limits_ta_9b428df5" ON public."workforce_approval_limits" ("target_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_data_scopes_workforce_data_scopes_assigned_b_2cf4d102" ON public."workforce_data_scopes" ("assigned_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_data_scopes_workforce_data_scopes_company_id_c15c72ef" ON public."workforce_data_scopes" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_data_scopes_workforce_data_scopes_revoked_by_f3136122" ON public."workforce_data_scopes" ("revoked_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_data_scopes_workforce_data_scopes_target_pro_f1fb3ee2" ON public."workforce_data_scopes" ("target_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_member_roles_workforce_member_roles_assigned_885d252b" ON public."workforce_member_roles" ("assigned_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_member_roles_workforce_member_roles_company__e45a9aa5" ON public."workforce_member_roles" ("company_id", "approval_request_id");

-- WAVE 4: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_member_roles_workforce_member_roles_company__1ee549ce" ON public."workforce_member_roles" ("company_id", "role_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_member_roles_workforce_member_roles_employee_b2265ab6" ON public."workforce_member_roles" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_member_roles_workforce_member_roles_profile__c061eb7a" ON public."workforce_member_roles" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_member_roles_workforce_member_roles_revoked__7888d08b" ON public."workforce_member_roles" ("revoked_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_module_access_workforce_module_access_assign_84260953" ON public."workforce_module_access" ("assigned_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_module_access_workforce_module_access_compan_c808aa56" ON public."workforce_module_access" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_module_access_workforce_module_access_revoke_ed8d2912" ON public."workforce_module_access" ("revoked_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_module_access_workforce_module_access_target_863da3df" ON public."workforce_module_access" ("target_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_permission_conflicts_workforce_permission_co_ff4b3c5b" ON public."workforce_permission_conflicts" ("company_id", "permission_a_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_permission_conflicts_workforce_permission_co_09dc75b9" ON public."workforce_permission_conflicts" ("company_id", "permission_b_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_permission_conflicts_workforce_permission_co_288e93fe" ON public."workforce_permission_conflicts" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_permission_conflicts_workforce_permission_co_864e453e" ON public."workforce_permission_conflicts" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_roles_workforce_roles_created_by_fkey_fk_idx_e8fd23a6" ON public."workforce_roles" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "workforce_roles_workforce_roles_updated_by_fkey_fk_idx_2cf02e47" ON public."workforce_roles" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_discount_rules_pos_discount_rules_account_company__603a2e01" ON public."pos_discount_rules" ("company_id", "contra_revenue_account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_discount_rules_pos_discount_rules_approval_company_90a64395" ON public."pos_discount_rules" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_discount_rules_pos_discount_rules_created_by_fkey__98954a99" ON public."pos_discount_rules" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_discount_rules_pos_discount_rules_inventory_item_i_b0e971f8" ON public."pos_discount_rules" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_discount_rules_pos_discount_rules_updated_by_fkey__e4c29d94" ON public."pos_discount_rules" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_ledger_pos_loyalty_ledger_created_by_fkey__050711e2" ON public."pos_loyalty_ledger" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_ledger_pos_loyalty_ledger_updated_by_fkey__a1c4d29e" ON public."pos_loyalty_ledger" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_members_pos_loyalty_members_created_by_fke_1d23d08e" ON public."pos_loyalty_members" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_members_pos_loyalty_members_customer_id_fk_df8f6eea" ON public."pos_loyalty_members" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_members_pos_loyalty_members_updated_by_fke_c7e61c91" ON public."pos_loyalty_members" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_programs_pos_loyalty_programs_account_comp_4888a735" ON public."pos_loyalty_programs" ("company_id", "points_liability_account_id");

-- WAVE 5: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_programs_pos_loyalty_programs_approval_com_a4f96c7c" ON public."pos_loyalty_programs" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_programs_pos_loyalty_programs_created_by_f_8aeaedfd" ON public."pos_loyalty_programs" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_programs_pos_loyalty_programs_updated_by_f_929cadb7" ON public."pos_loyalty_programs" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_applie_e77e35c7" ON public."pos_loyalty_redemptions" ("applied_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_approv_d3b34cab" ON public."pos_loyalty_redemptions" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_create_3d83d4f4" ON public."pos_loyalty_redemptions" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_journa_093ba6a3" ON public."pos_loyalty_redemptions" ("company_id", "journal_batch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_reward_ee890301" ON public."pos_loyalty_redemptions" ("company_id", "reward_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_sale_c_7a1aa3fd" ON public."pos_loyalty_redemptions" ("company_id", "sale_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_redemptions_pos_loyalty_redemptions_update_3d90496e" ON public."pos_loyalty_redemptions" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_rewards_pos_loyalty_rewards_approval_compa_3fd7532e" ON public."pos_loyalty_rewards" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_rewards_pos_loyalty_rewards_created_by_fke_1b80ca6a" ON public."pos_loyalty_rewards" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_rewards_pos_loyalty_rewards_inventory_item_139b4abd" ON public."pos_loyalty_rewards" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_loyalty_rewards_pos_loyalty_rewards_updated_by_fke_cef8d442" ON public."pos_loyalty_rewards" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_promotion_items_pos_promotion_items_created_by_fke_ff714b20" ON public."pos_promotion_items" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_promotion_items_pos_promotion_items_inventory_item_b3b85d26" ON public."pos_promotion_items" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_promotion_items_pos_promotion_items_updated_by_fke_1c9ab8c3" ON public."pos_promotion_items" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_promotions_pos_promotions_approval_company_fkey_fk_aa851e27" ON public."pos_promotions" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_promotions_pos_promotions_created_by_fkey_fk_idx_ba472488" ON public."pos_promotions" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_promotions_pos_promotions_updated_by_fkey_fk_idx_dc1e4737" ON public."pos_promotions" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_registers_pos_registers_branch_id_fkey_fk_idx_381cf4e2" ON public."pos_registers" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_registers_pos_registers_created_by_fkey_fk_idx_bd530f49" ON public."pos_registers" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_registers_pos_registers_updated_by_fkey_fk_idx_4975ef7b" ON public."pos_registers" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_registers_pos_registers_warehouse_id_fkey_fk_idx_e9ccc418" ON public."pos_registers" ("warehouse_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_commits_pos_return_commits_created_by_fkey__483f6ab5" ON public."pos_return_commits" ("created_by");

-- WAVE 6: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_commits_pos_return_commits_return_id_fkey_f_71932a45" ON public."pos_return_commits" ("return_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_approval_company_6f8f86b8" ON public."pos_return_headers" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_cashier_id_fkey__ee2810e6" ON public."pos_return_headers" ("cashier_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_created_by_fkey__309f2ca6" ON public."pos_return_headers" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_journal_company__ba66943f" ON public."pos_return_headers" ("company_id", "journal_batch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_legacy_pos_retur_c39fbf33" ON public."pos_return_headers" ("legacy_pos_return_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_posted_by_fkey_f_c116fd00" ON public."pos_return_headers" ("posted_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_register_company_7f026455" ON public."pos_return_headers" ("company_id", "register_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_shift_company_fk_1e5c0d77" ON public."pos_return_headers" ("company_id", "shift_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_terminal_company_72aa7d8e" ON public."pos_return_headers" ("company_id", "terminal_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_headers_pos_return_headers_updated_by_fkey__df9249ec" ON public."pos_return_headers" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_lines_pos_return_lines_created_by_fkey_fk_i_82c2cc62" ON public."pos_return_lines" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_return_lines_pos_return_lines_updated_by_fkey_fk_i_82ed1b5c" ON public."pos_return_lines" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_applied_by_f_dd7adc50" ON public."pos_sale_adjustments" ("applied_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_approval_com_53a4b9ce" ON public."pos_sale_adjustments" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_created_by_f_02c221d9" ON public."pos_sale_adjustments" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_discount_com_75226346" ON public."pos_sale_adjustments" ("company_id", "discount_rule_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_journal_comp_22037666" ON public."pos_sale_adjustments" ("company_id", "journal_batch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_line_company_ce331ec1" ON public."pos_sale_adjustments" ("company_id", "sale_line_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_promotion_co_8d27f816" ON public."pos_sale_adjustments" ("company_id", "promotion_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_adjustments_pos_sale_adjustments_updated_by_f_1d65cf3e" ON public."pos_sale_adjustments" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_cashier_id_fkey_fk_i_d3295256" ON public."pos_sale_headers" ("cashier_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_created_by_fkey_fk_i_5e45ed5d" ON public."pos_sale_headers" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_customer_id_fkey_fk__5384df8f" ON public."pos_sale_headers" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_legacy_pos_transacti_eb2529dd" ON public."pos_sale_headers" ("legacy_pos_transaction_id");

-- WAVE 7: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_register_company_fke_92909672" ON public."pos_sale_headers" ("company_id", "register_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_terminal_company_fke_62676aea" ON public."pos_sale_headers" ("company_id", "terminal_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_headers_pos_sale_headers_updated_by_fkey_fk_i_fbe46579" ON public."pos_sale_headers" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_lines_pos_sale_lines_created_by_fkey_fk_idx_06661dba" ON public."pos_sale_lines" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_lines_pos_sale_lines_inventory_item_id_fkey_f_18cdeb88" ON public."pos_sale_lines" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_lines_pos_sale_lines_legacy_pos_transaction_i_b556b3f9" ON public."pos_sale_lines" ("legacy_pos_transaction_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_lines_pos_sale_lines_updated_by_fkey_fk_idx_7d5b6c03" ON public."pos_sale_lines" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tax_lines_pos_sale_tax_lines_created_by_fkey__61887ae3" ON public."pos_sale_tax_lines" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tax_lines_pos_sale_tax_lines_line_company_fke_09f5156e" ON public."pos_sale_tax_lines" ("company_id", "sale_line_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tax_lines_pos_sale_tax_lines_rule_company_fke_334bb2ab" ON public."pos_sale_tax_lines" ("company_id", "tax_rule_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tax_lines_pos_sale_tax_lines_updated_by_fkey__8332e531" ON public."pos_sale_tax_lines" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tenders_pos_sale_tenders_created_by_fkey_fk_i_db95e516" ON public."pos_sale_tenders" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tenders_pos_sale_tenders_journal_company_fkey_9a113778" ON public."pos_sale_tenders" ("company_id", "journal_batch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sale_tenders_pos_sale_tenders_updated_by_fkey_fk_i_a1fbbb7f" ON public."pos_sale_tenders" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_cash_movements_pos_shift_cash_movements_crea_2de85829" ON public."pos_shift_cash_movements" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_cash_movements_pos_shift_cash_movements_lega_7a02a56b" ON public."pos_shift_cash_movements" ("legacy_pos_cash_movement_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_cash_movements_pos_shift_cash_movements_post_93ec1e65" ON public."pos_shift_cash_movements" ("posted_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_cash_movements_pos_shift_cash_movements_reve_2e76a736" ON public."pos_shift_cash_movements" ("company_id", "reversal_of_movement_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_cash_movements_pos_shift_cash_movements_upda_be685397" ON public."pos_shift_cash_movements" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_sessions_pos_shift_sessions_cashier_id_fkey__403e7713" ON public."pos_shift_sessions" ("cashier_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_sessions_pos_shift_sessions_closed_by_fkey_f_c094a253" ON public."pos_shift_sessions" ("closed_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_sessions_pos_shift_sessions_created_by_fkey__05d46d1f" ON public."pos_shift_sessions" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_sessions_pos_shift_sessions_legacy_pos_shift_21ef9a89" ON public."pos_shift_sessions" ("legacy_pos_shift_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_shift_sessions_pos_shift_sessions_updated_by_fkey__8eb53e58" ON public."pos_shift_sessions" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sync_devices_pos_sync_devices_created_by_fkey_fk_i_7024e1ec" ON public."pos_sync_devices" ("created_by");

-- WAVE 8: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sync_devices_pos_sync_devices_terminal_company_fke_cc0cfcc0" ON public."pos_sync_devices" ("company_id", "terminal_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sync_devices_pos_sync_devices_updated_by_fkey_fk_i_08384485" ON public."pos_sync_devices" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sync_events_pos_sync_events_created_by_fkey_fk_idx_9c80eb40" ON public."pos_sync_events" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_sync_events_pos_sync_events_transaction_id_fkey_fk_5af443a6" ON public."pos_sync_events" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_tax_rules_pos_tax_rules_account_company_fkey_fk_id_537cd3e6" ON public."pos_tax_rules" ("company_id", "tax_account_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_tax_rules_pos_tax_rules_approval_company_fkey_fk_i_0adfeab0" ON public."pos_tax_rules" ("company_id", "approval_request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_tax_rules_pos_tax_rules_created_by_fkey_fk_idx_75b4d023" ON public."pos_tax_rules" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_tax_rules_pos_tax_rules_inventory_item_id_fkey_fk__d174efda" ON public."pos_tax_rules" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_tax_rules_pos_tax_rules_updated_by_fkey_fk_idx_fa420c70" ON public."pos_tax_rules" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_terminals_pos_terminals_created_by_fkey_fk_idx_8a649c77" ON public."pos_terminals" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_terminals_pos_terminals_updated_by_fkey_fk_idx_5e5159c8" ON public."pos_terminals" ("updated_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_transaction_commits_pos_transaction_commits_create_e873cf1e" ON public."pos_transaction_commits" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "pos_transaction_commits_pos_transaction_commits_transa_1392b754" ON public."pos_transaction_commits" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "mfi_collateral_mfi_collateral_company_id_fkey_fk_idx_4b570996" ON public."mfi_collateral" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "mfi_guarantors_mfi_guarantors_company_id_fkey_fk_idx_fc34d91f" ON public."mfi_guarantors" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "mfi_staff_commissions_mfi_staff_commissions_company_id_472ed6d6" ON public."mfi_staff_commissions" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_announcements_community_group_announce_9dfee988" ON public."community_group_announcements" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_announcements_community_group_announce_8626e694" ON public."community_group_announcements" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_approvals_community_group_approvals_co_9d7a8ee8" ON public."community_group_approvals" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_approvals_community_group_approvals_gr_04502949" ON public."community_group_approvals" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_assets_community_group_assets_group_id_23b54ff6" ON public."community_group_assets" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_attendance_community_group_attendance__fb081797" ON public."community_group_attendance" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_attendance_community_group_attendance__4faf49ae" ON public."community_group_attendance" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_audit_log_community_group_audit_log_co_0157548a" ON public."community_group_audit_log" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_budgets_community_group_budgets_compan_9b31de46" ON public."community_group_budgets" ("company_id");

-- WAVE 9: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_budgets_community_group_budgets_group__2ff6a13f" ON public."community_group_budgets" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_budgets_community_group_budgets_projec_8bd42807" ON public."community_group_budgets" ("project_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_committee_members_community_group_comm_204b5e84" ON public."community_group_committee_members" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_committee_members_community_group_comm_e601c14b" ON public."community_group_committee_members" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_committees_community_group_committees__e4a1b6f6" ON public."community_group_committees" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_committees_community_group_committees__06bc0f2e" ON public."community_group_committees" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_contributions_community_group_contribu_747fb852" ON public."community_group_contributions" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_documents_community_group_documents_co_e38a14d1" ON public."community_group_documents" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_documents_community_group_documents_gr_b2a665d6" ON public."community_group_documents" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_events_community_group_events_company__97bdff9b" ON public."community_group_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_events_community_group_events_group_id_bd4bd712" ON public."community_group_events" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_expenses_community_group_expenses_comp_57d2fc4a" ON public."community_group_expenses" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_expenses_community_group_expenses_grou_baa1d4d0" ON public."community_group_expenses" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_expenses_community_group_expenses_proj_2951768a" ON public."community_group_expenses" ("project_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_fundraising_community_group_fundraisin_fff80fb3" ON public."community_group_fundraising" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_fundraising_community_group_fundraisin_2df27cf4" ON public."community_group_fundraising" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_fundraising_community_group_fundraisin_8dc1bcf5" ON public."community_group_fundraising" ("project_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_income_community_group_income_company__93d34606" ON public."community_group_income" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_income_community_group_income_group_id_34cf23c0" ON public."community_group_income" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_loan_guarantors_community_group_loan_g_69502c7e" ON public."community_group_loan_guarantors" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_loan_guarantors_community_group_loan_g_fa155d5c" ON public."community_group_loan_guarantors" ("guarantor_member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_loan_penalties_community_group_loan_pe_0e337a27" ON public."community_group_loan_penalties" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_loan_penalties_community_group_loan_pe_8de47982" ON public."community_group_loan_penalties" ("loan_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_loan_repayments_community_group_loan_r_805ec481" ON public."community_group_loan_repayments" ("loan_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_loans_community_group_loans_member_id__bc1cbdb5" ON public."community_group_loans" ("member_id");

-- WAVE 10: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_meetings_community_group_meetings_chai_5d797c13" ON public."community_group_meetings" ("chairperson_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_meetings_community_group_meetings_comp_0a2a49fb" ON public."community_group_meetings" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_messages_community_group_messages_comp_0aceff25" ON public."community_group_messages" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_messages_community_group_messages_grou_09043697" ON public."community_group_messages" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_messages_community_group_messages_send_c2c9a20d" ON public."community_group_messages" ("sender_member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_notifications_community_group_notifica_af727fa6" ON public."community_group_notifications" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_notifications_community_group_notifica_6edfac69" ON public."community_group_notifications" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_notifications_community_group_notifica_37f3e698" ON public."community_group_notifications" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_projects_community_group_projects_grou_88619d77" ON public."community_group_projects" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_savings_community_group_savings_compan_cfcf002a" ON public."community_group_savings" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_savings_community_group_savings_group__7e143a78" ON public."community_group_savings" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_savings_community_group_savings_member_dddeaf00" ON public."community_group_savings" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_vote_ballots_community_group_vote_ball_c72eecd9" ON public."community_group_vote_ballots" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_vote_ballots_community_group_vote_ball_9f9feb7c" ON public."community_group_vote_ballots" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_vote_ballots_community_group_vote_ball_f3a1c447" ON public."community_group_vote_ballots" ("option_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_vote_options_community_group_vote_opti_83e8c8d7" ON public."community_group_vote_options" ("candidate_member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_vote_options_community_group_vote_opti_f3b1105e" ON public."community_group_vote_options" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_vote_options_community_group_vote_opti_7a6609ae" ON public."community_group_vote_options" ("vote_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_votes_community_group_votes_company_id_d8cd1c08" ON public."community_group_votes" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_votes_community_group_votes_group_id_f_02c72303" ON public."community_group_votes" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_welfare_claims_community_group_welfare_5e29d9ff" ON public."community_group_welfare_claims" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_welfare_claims_community_group_welfare_d127f274" ON public."community_group_welfare_claims" ("group_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "community_group_welfare_claims_community_group_welfare_b586a786" ON public."community_group_welfare_claims" ("member_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_folio_lines_hospitality_folio_lines_compan_63959759" ON public."hospitality_folio_lines" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_folio_lines_hospitality_folio_lines_folio__b7ab8514" ON public."hospitality_folio_lines" ("folio_id");

-- WAVE 11: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_folios_hospitality_folios_guest_id_fkey_fk_e8330edb" ON public."hospitality_folios" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_folios_hospitality_folios_property_id_fkey_96bd61da" ON public."hospitality_folios" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guests_hospitality_guests_profile_id_fkey__50204b1d" ON public."hospitality_guests" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_housekeeping_tasks_hospitality_housekeepin_1990c22a" ON public."hospitality_housekeeping_tasks" ("assigned_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_housekeeping_tasks_hospitality_housekeepin_2b6fda7a" ON public."hospitality_housekeeping_tasks" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_housekeeping_tasks_hospitality_housekeepin_70ed9612" ON public."hospitality_housekeeping_tasks" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_housekeeping_tasks_hospitality_housekeepin_b7fb2647" ON public."hospitality_housekeeping_tasks" ("room_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_payments_hospitality_payments_company_id_f_00605f43" ON public."hospitality_payments" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_payments_hospitality_payments_folio_id_fke_5cfcc5af" ON public."hospitality_payments" ("folio_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_properties_hospitality_properties_branch_i_06ead0bc" ON public."hospitality_properties" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_reservations_hospitality_reservations_gues_1342685f" ON public."hospitality_reservations" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_reservations_hospitality_reservations_prop_1cfab7a4" ON public."hospitality_reservations" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_reservations_hospitality_reservations_room_314b4c84" ON public."hospitality_reservations" ("room_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_reservations_hospitality_reservations_room_3657fe9b" ON public."hospitality_reservations" ("room_type_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_room_types_hospitality_room_types_company__b9f36edd" ON public."hospitality_room_types" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_rooms_hospitality_rooms_company_id_fkey_fk_e019ea9f" ON public."hospitality_rooms" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_rooms_hospitality_rooms_room_type_id_fkey__bed17b0e" ON public."hospitality_rooms" ("room_type_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_payroll_items_hr_payroll_items_employee_id_fkey_fk__94ba19ad" ON public."hr_payroll_items" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_payslips_hr_payslips_document_id_fkey_fk_idx_f89b5954" ON public."hr_payslips" ("document_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_payslips_hr_payslips_employee_id_fkey_fk_idx_1fca4c3b" ON public."hr_payslips" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_positions_hr_positions_department_id_fkey_fk_idx_7e88cc7e" ON public."hr_positions" ("department_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_menu_items_restaurant_menu_items_category_i_90052a1f" ON public."restaurant_menu_items" ("category_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_menu_items_restaurant_menu_items_company_id_fe520fde" ON public."restaurant_menu_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_menu_items_restaurant_menu_items_inventory__1507a077" ON public."restaurant_menu_items" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_orders_restaurant_orders_customer_id_fkey_f_4ebd40ba" ON public."restaurant_orders" ("customer_id");

-- WAVE 12: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_orders_restaurant_orders_hotel_folio_id_fke_cf12797a" ON public."restaurant_orders" ("hotel_folio_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_orders_restaurant_orders_outlet_id_fkey_fk__78ad5e06" ON public."restaurant_orders" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_orders_restaurant_orders_reservation_id_fke_4ed29b82" ON public."restaurant_orders" ("reservation_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_orders_restaurant_orders_table_id_fkey_fk_i_89579ac9" ON public."restaurant_orders" ("table_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_orders_restaurant_orders_waiter_employee_id_5efcffdb" ON public."restaurant_orders" ("waiter_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_outlets_restaurant_outlets_branch_id_fkey_f_ec3fb317" ON public."restaurant_outlets" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_outlets_restaurant_outlets_property_id_fkey_80267a75" ON public."restaurant_outlets" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_tables_restaurant_tables_area_id_fkey_fk_id_85cd3ba7" ON public."restaurant_tables" ("area_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_tables_restaurant_tables_company_id_fkey_fk_839e5650" ON public."restaurant_tables" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_tables_restaurant_tables_current_order_id_f_412d0ed3" ON public."restaurant_tables" ("current_order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_invoice_items_sales_invoice_items_header_fkey_fk_81df29a2" ON public."sales_invoice_items" ("invoice_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_invoices_sales_invoices_order_fkey_fk_idx_4d044039" ON public."sales_invoices" ("order_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_order_items_sales_order_items_header_fkey_fk_idx_1ed98cee" ON public."sales_order_items" ("order_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_payments_sales_payments_invoice_fkey_fk_idx_822c4bd9" ON public."sales_payments" ("invoice_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_ticket_messages_support_ticket_messages_sender_09565a29" ON public."support_ticket_messages" ("sender_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_ticket_messages_support_ticket_messages_ticket_66fcf49d" ON public."support_ticket_messages" ("ticket_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_tickets_support_tickets_assigned_profile_id_fk_c131e48e" ON public."support_tickets" ("assigned_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_tickets_support_tickets_team_id_fkey_fk_idx_36180eaa" ON public."support_tickets" ("team_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "billing_plan_audit_log_billing_plan_audit_log_company__fb7dc8f0" ON public."billing_plan_audit_log" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_alerts_fleet_alerts_acknowledged_by_fkey_fk_idx_c4e7d653" ON public."fleet_alerts" ("acknowledged_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_audit_events_fleet_audit_events_actor_profile_id_b764aafe" ON public."fleet_audit_events" ("actor_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_audit_events_fleet_audit_events_company_id_fkey__7e251907" ON public."fleet_audit_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_driver_assignments_fleet_driver_assignments_assi_59f19a5e" ON public."fleet_driver_assignments" ("assigned_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_driver_assignments_fleet_driver_assignments_comp_c61c050a" ON public."fleet_driver_assignments" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_drivers_fleet_drivers_created_by_fkey_fk_idx_abbe452a" ON public."fleet_drivers" ("created_by");

-- WAVE 13: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_drivers_fleet_drivers_employee_id_fkey_fk_idx_8eabd3fa" ON public."fleet_drivers" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_drivers_fleet_drivers_profile_id_fkey_fk_idx_f33f479c" ON public."fleet_drivers" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_fuel_cards_fleet_fuel_cards_vehicle_id_fkey_fk_i_b13ce523" ON public."fleet_fuel_cards" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_fuel_transactions_fleet_fuel_transactions_create_756f6eb5" ON public."fleet_fuel_transactions" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_fuel_transactions_fleet_fuel_transactions_fuel_c_99460403" ON public."fleet_fuel_transactions" ("fuel_card_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_fuel_transactions_fleet_fuel_transactions_trip_i_1a393247" ON public."fleet_fuel_transactions" ("trip_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_fuel_transactions_fleet_fuel_transactions_vehicl_c2b032e9" ON public."fleet_fuel_transactions" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_incidents_fleet_incidents_company_id_fkey_fk_idx_f0fa0ab1" ON public."fleet_incidents" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_incidents_fleet_incidents_created_by_fkey_fk_idx_2501bc52" ON public."fleet_incidents" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_incidents_fleet_incidents_driver_id_fkey_fk_idx_acaa37ee" ON public."fleet_incidents" ("driver_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_incidents_fleet_incidents_trip_id_fkey_fk_idx_39634ad1" ON public."fleet_incidents" ("trip_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_incidents_fleet_incidents_vehicle_id_fkey_fk_idx_3106d4a9" ON public."fleet_incidents" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_jobs_fleet_maintenance_jobs_approved_21234a6c" ON public."fleet_maintenance_jobs" ("approved_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_jobs_fleet_maintenance_jobs_created__b9e5d921" ON public."fleet_maintenance_jobs" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_jobs_fleet_maintenance_jobs_plan_id__0675d8e1" ON public."fleet_maintenance_jobs" ("plan_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_jobs_fleet_maintenance_jobs_vehicle__1a4b457d" ON public."fleet_maintenance_jobs" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_jobs_fleet_maintenance_jobs_workshop_e0776f27" ON public."fleet_maintenance_jobs" ("workshop_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_plans_fleet_maintenance_plans_compan_a20867c6" ON public."fleet_maintenance_plans" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_plans_fleet_maintenance_plans_create_6dfeee45" ON public."fleet_maintenance_plans" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_maintenance_plans_fleet_maintenance_plans_vehicl_295586a9" ON public."fleet_maintenance_plans" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_routes_fleet_routes_created_by_fkey_fk_idx_fa4c515d" ON public."fleet_routes" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_service_records_fleet_service_records_company_id_8dfd5392" ON public."fleet_service_records" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_service_records_fleet_service_records_created_by_2988ab37" ON public."fleet_service_records" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_service_records_fleet_service_records_maintenanc_c67d075b" ON public."fleet_service_records" ("maintenance_job_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_service_records_fleet_service_records_vehicle_id_cb2e1a24" ON public."fleet_service_records" ("vehicle_id");

-- WAVE 14: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_spare_parts_fleet_spare_parts_inventory_item_id__194dc3e2" ON public."fleet_spare_parts" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_telematics_events_fleet_telematics_events_vehicl_5605844b" ON public."fleet_telematics_events" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_trips_fleet_trips_approved_by_fkey_fk_idx_755081a4" ON public."fleet_trips" ("approved_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_trips_fleet_trips_created_by_fkey_fk_idx_7edfb7d3" ON public."fleet_trips" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_trips_fleet_trips_driver_id_fkey_fk_idx_e9f50d13" ON public."fleet_trips" ("driver_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_trips_fleet_trips_route_id_fkey_fk_idx_b4038964" ON public."fleet_trips" ("route_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_trips_fleet_trips_vehicle_id_fkey_fk_idx_8fa05ae0" ON public."fleet_trips" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_tyres_fleet_tyres_company_id_fkey_fk_idx_939a8b01" ON public."fleet_tyres" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_vehicle_documents_fleet_vehicle_documents_create_d8eea66b" ON public."fleet_vehicle_documents" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_vehicle_documents_fleet_vehicle_documents_vehicl_131933d5" ON public."fleet_vehicle_documents" ("vehicle_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_vehicles_fleet_vehicles_category_id_fkey_fk_idx_3707fc3c" ON public."fleet_vehicles" ("category_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "fleet_vehicles_fleet_vehicles_created_by_fkey_fk_idx_ce5c2b2a" ON public."fleet_vehicles" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_audit_log_hospitality_audit_log_company_id_d692cef0" ON public."hospitality_audit_log" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_complaints_hospitality_complaints_company__c3687e24" ON public."hospitality_complaints" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_complaints_hospitality_complaints_guest_id_9b475579" ON public."hospitality_complaints" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_complaints_hospitality_complaints_reservat_58e875fa" ON public."hospitality_complaints" ("reservation_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_event_venues_hospitality_event_venues_comp_048f01d4" ON public."hospitality_event_venues" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_events_hospitality_events_company_id_fkey__428d14fc" ON public."hospitality_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_events_hospitality_events_guest_id_fkey_fk_1cda5950" ON public."hospitality_events" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_events_hospitality_events_property_id_fkey_a49593e1" ON public."hospitality_events" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_events_hospitality_events_venue_id_fkey_fk_f937c111" ON public."hospitality_events" ("venue_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_finance_reconciliations_hospitality_financ_19202b2f" ON public."hospitality_finance_reconciliations" ("journal_entry_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_finance_reconciliations_hospitality_financ_f0ef8269" ON public."hospitality_finance_reconciliations" ("pos_transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_finance_reconciliations_hospitality_financ_73467666" ON public."hospitality_finance_reconciliations" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_kyc_hospitality_guest_kyc_company_id_83656313" ON public."hospitality_guest_kyc" ("company_id");

-- WAVE 15: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_kyc_hospitality_guest_kyc_document_i_39274e35" ON public."hospitality_guest_kyc" ("document_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_kyc_hospitality_guest_kyc_guest_id_f_13e2e66b" ON public."hospitality_guest_kyc" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_requests_hospitality_guest_requests__d3dc917a" ON public."hospitality_guest_requests" ("assigned_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_requests_hospitality_guest_requests__849a2613" ON public."hospitality_guest_requests" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_requests_hospitality_guest_requests__e02e51c5" ON public."hospitality_guest_requests" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_guest_requests_hospitality_guest_requests__11230fdb" ON public."hospitality_guest_requests" ("reservation_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_laundry_orders_hospitality_laundry_orders__1c01f925" ON public."hospitality_laundry_orders" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_laundry_orders_hospitality_laundry_orders__a890fc5e" ON public."hospitality_laundry_orders" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_laundry_orders_hospitality_laundry_orders__e458170d" ON public."hospitality_laundry_orders" ("reservation_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_loyalty_accounts_hospitality_loyalty_accou_0e0476c7" ON public."hospitality_loyalty_accounts" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_maintenance_requests_hospitality_maintenan_c26db891" ON public."hospitality_maintenance_requests" ("assigned_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_maintenance_requests_hospitality_maintenan_0a358bca" ON public."hospitality_maintenance_requests" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_maintenance_requests_hospitality_maintenan_a7ed5c54" ON public."hospitality_maintenance_requests" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_maintenance_requests_hospitality_maintenan_075b4ff6" ON public."hospitality_maintenance_requests" ("room_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_menu_items_hospitality_menu_items_company__ddb90435" ON public."hospitality_menu_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_menu_items_hospitality_menu_items_inventor_b9ae430a" ON public."hospitality_menu_items" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_menu_items_hospitality_menu_items_menu_id__19f67fef" ON public."hospitality_menu_items" ("menu_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_menus_hospitality_menus_company_id_fkey_fk_22247943" ON public."hospitality_menus" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_menus_hospitality_menus_property_id_fkey_f_a1445b9e" ON public."hospitality_menus" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_minibar_postings_hospitality_minibar_posti_12ffa694" ON public."hospitality_minibar_postings" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_minibar_postings_hospitality_minibar_posti_27ec1127" ON public."hospitality_minibar_postings" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_minibar_postings_hospitality_minibar_posti_11be1f6d" ON public."hospitality_minibar_postings" ("reservation_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_notifications_hospitality_notifications_co_ba17c600" ON public."hospitality_notifications" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_notifications_hospitality_notifications_em_2c2c6063" ON public."hospitality_notifications" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_notifications_hospitality_notifications_pr_6ba55c89" ON public."hospitality_notifications" ("profile_id");

-- WAVE 16: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_order_lines_hospitality_order_lines_compan_ef95edb9" ON public."hospitality_order_lines" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_order_lines_hospitality_order_lines_menu_i_22da6a87" ON public."hospitality_order_lines" ("menu_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_order_lines_hospitality_order_lines_order__e4937507" ON public."hospitality_order_lines" ("order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_orders_hospitality_orders_folio_id_fkey_fk_1c3f9db4" ON public."hospitality_orders" ("folio_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_orders_hospitality_orders_property_id_fkey_9986d812" ON public."hospitality_orders" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_orders_hospitality_orders_reservation_id_f_8e709537" ON public."hospitality_orders" ("reservation_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_orders_hospitality_orders_table_id_fkey_fk_a941f656" ON public."hospitality_orders" ("table_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_rate_plans_hospitality_rate_plans_company__02bdbe03" ON public."hospitality_rate_plans" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_rate_plans_hospitality_rate_plans_property_e6faf2cb" ON public."hospitality_rate_plans" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_rate_plans_hospitality_rate_plans_room_typ_8ab3c280" ON public."hospitality_rate_plans" ("room_type_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_restaurant_tables_hospitality_restaurant_t_3a96206d" ON public."hospitality_restaurant_tables" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hospitality_taxes_hospitality_taxes_property_id_fkey_f_e5975ab7" ON public."hospitality_taxes" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_announcements_hr_announcements_company_id_fkey_fk_i_be4f414e" ON public."hr_announcements" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_announcements_hr_announcements_department_id_fkey_f_77c0a9c7" ON public."hr_announcements" ("department_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_approval_requests_hr_approval_requests_requester_em_ddafbade" ON public."hr_approval_requests" ("requester_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_approval_requests_hr_approval_requests_subject_empl_40b0da8a" ON public."hr_approval_requests" ("subject_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_approval_steps_hr_approval_steps_approver_profile_i_a2ca238a" ON public."hr_approval_steps" ("approver_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_approval_steps_hr_approval_steps_company_id_fkey_fk_c35783f6" ON public."hr_approval_steps" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_benefit_enrollments_hr_benefit_enrollments_benefit__c5453753" ON public."hr_benefit_enrollments" ("benefit_plan_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_benefit_enrollments_hr_benefit_enrollments_employee_e822b50f" ON public."hr_benefit_enrollments" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_employee_documents_hr_employee_documents_document_i_574a14ad" ON public."hr_employee_documents" ("document_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_employee_documents_hr_employee_documents_employee_i_5e9fb1a0" ON public."hr_employee_documents" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_expense_claims_hr_expense_claims_document_id_fkey_f_791277c9" ON public."hr_expense_claims" ("document_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_expense_claims_hr_expense_claims_employee_id_fkey_f_36e1dbe0" ON public."hr_expense_claims" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_expense_claims_hr_expense_claims_finance_expense_id_68d3fd76" ON public."hr_expense_claims" ("finance_expense_id");

-- WAVE 17: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_goal_updates_hr_goal_updates_company_id_fkey_fk_idx_3d87a4fa" ON public."hr_goal_updates" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_goal_updates_hr_goal_updates_employee_id_fkey_fk_id_516008f8" ON public."hr_goal_updates" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_goal_updates_hr_goal_updates_goal_id_fkey_fk_idx_3450af76" ON public."hr_goal_updates" ("goal_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_goals_hr_goals_employee_id_fkey_fk_idx_e30ae4c7" ON public."hr_goals" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_goals_hr_goals_owner_employee_id_fkey_fk_idx_053c8e83" ON public."hr_goals" ("owner_employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_holidays_hr_holidays_branch_id_fkey_fk_idx_871690ea" ON public."hr_holidays" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_leave_balances_hr_leave_balances_employee_id_fkey_f_80950b87" ON public."hr_leave_balances" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_leave_balances_hr_leave_balances_leave_policy_id_fk_eaafa66f" ON public."hr_leave_balances" ("leave_policy_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_notifications_hr_notifications_employee_id_fkey_fk__78307f31" ON public."hr_notifications" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_notifications_hr_notifications_profile_id_fkey_fk_i_946b3c50" ON public."hr_notifications" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_offboarding_cases_hr_offboarding_cases_employee_id__b054c9d6" ON public."hr_offboarding_cases" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_onboarding_cases_hr_onboarding_cases_employee_id_fk_00d63168" ON public."hr_onboarding_cases" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_onboarding_tasks_hr_onboarding_tasks_company_id_fke_180d994b" ON public."hr_onboarding_tasks" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_onboarding_tasks_hr_onboarding_tasks_employee_id_fk_51ae6f20" ON public."hr_onboarding_tasks" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_onboarding_tasks_hr_onboarding_tasks_onboarding_cas_395a5fde" ON public."hr_onboarding_tasks" ("onboarding_case_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_service_requests_hr_service_requests_company_id_fke_922a704c" ON public."hr_service_requests" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_service_requests_hr_service_requests_employee_id_fk_fe89e6c4" ON public."hr_service_requests" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_shift_assignments_hr_shift_assignments_employee_id__bcdb107d" ON public."hr_shift_assignments" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_shift_assignments_hr_shift_assignments_shift_id_fke_283a5d52" ON public."hr_shift_assignments" ("shift_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_timesheet_entries_hr_timesheet_entries_company_id_f_2c4be356" ON public."hr_timesheet_entries" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_timesheet_entries_hr_timesheet_entries_timesheet_id_a43dbabf" ON public."hr_timesheet_entries" ("timesheet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_timesheets_hr_timesheets_employee_id_fkey_fk_idx_4763707e" ON public."hr_timesheets" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_training_assignments_hr_training_assignments_course_c5ac9c2e" ON public."hr_training_assignments" ("course_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "hr_training_assignments_hr_training_assignments_employ_ff917105" ON public."hr_training_assignments" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_agents_money_agent_agents_branch_id_fkey_f_a5d44de6" ON public."money_agent_agents" ("branch_id");

-- WAVE 18: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_agents_money_agent_agents_created_by_fkey__afe0c246" ON public."money_agent_agents" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_agents_money_agent_agents_profile_id_fkey__d17bd1e1" ON public."money_agent_agents" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_agents_money_agent_agents_supervisor_id_fk_f1914496" ON public."money_agent_agents" ("supervisor_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_alerts_money_agent_alerts_acknowledged_by__be4676c9" ON public."money_agent_alerts" ("acknowledged_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_alerts_money_agent_alerts_agent_id_fkey_fk_022d5915" ON public."money_agent_alerts" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_approvals_money_agent_approvals_decided_by_69227d9b" ON public."money_agent_approvals" ("decided_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_approvals_money_agent_approvals_requested__2dfdf9d1" ON public."money_agent_approvals" ("requested_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_approvals_money_agent_approvals_transactio_af86e2cb" ON public."money_agent_approvals" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_audit_events_money_agent_audit_events_acto_d70303c4" ON public."money_agent_audit_events" ("actor_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_audit_events_money_agent_audit_events_comp_8a5c0af2" ON public."money_agent_audit_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_branches_money_agent_branches_created_by_f_7711f9e7" ON public."money_agent_branches" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_commission_rules_money_agent_commission_ru_277bf00e" ON public."money_agent_commission_rules" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_customers_money_agent_customers_created_by_b7638547" ON public."money_agent_customers" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_customers_money_agent_customers_profile_id_ce0b169b" ON public."money_agent_customers" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_daily_summaries_money_agent_daily_summarie_b584595c" ON public."money_agent_daily_summaries" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_daily_summaries_money_agent_daily_summarie_cf2df3d1" ON public."money_agent_daily_summaries" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_fee_rules_money_agent_fee_rules_created_by_42637d82" ON public."money_agent_fee_rules" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_ledger_entries_money_agent_ledger_entries__0a2396fc" ON public."money_agent_ledger_entries" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_limits_money_agent_limits_agent_id_fkey_fk_e6f3b6d2" ON public."money_agent_limits" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_limits_money_agent_limits_created_by_fkey__20ebf22e" ON public."money_agent_limits" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_notifications_money_agent_notifications_ag_413337ab" ON public."money_agent_notifications" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_notifications_money_agent_notifications_co_eb9858fc" ON public."money_agent_notifications" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_notifications_money_agent_notifications_tr_5cdab481" ON public."money_agent_notifications" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_pin_credentials_money_agent_pin_credential_74a467a1" ON public."money_agent_pin_credentials" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_receipts_money_agent_receipts_transaction__5db2b52c" ON public."money_agent_receipts" ("transaction_id");

-- WAVE 19: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_reconciliations_money_agent_reconciliation_56f54714" ON public."money_agent_reconciliations" ("reviewed_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_reconciliations_money_agent_reconciliation_5bdc39cd" ON public."money_agent_reconciliations" ("settlement_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_risk_events_money_agent_risk_events_agent__3a5e4e58" ON public."money_agent_risk_events" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_risk_events_money_agent_risk_events_compan_d3ec96ab" ON public."money_agent_risk_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_risk_events_money_agent_risk_events_resolv_b2675f4a" ON public."money_agent_risk_events" ("resolved_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_risk_events_money_agent_risk_events_transa_8c4b035f" ON public."money_agent_risk_events" ("transaction_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_services_money_agent_services_created_by_f_681738fb" ON public."money_agent_services" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_settlements_money_agent_settlements_agent__38a6faab" ON public."money_agent_settlements" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_settlements_money_agent_settlements_branch_dd853b82" ON public."money_agent_settlements" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_settlements_money_agent_settlements_settle_0a2f7ce0" ON public."money_agent_settlements" ("settled_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_settlements_money_agent_settlements_submit_3640d0d1" ON public."money_agent_settlements" ("submitted_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_transactions_money_agent_transactions_agen_7fb76cf6" ON public."money_agent_transactions" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_transactions_money_agent_transactions_bran_8657c282" ON public."money_agent_transactions" ("branch_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_transactions_money_agent_transactions_crea_6d1f7d7d" ON public."money_agent_transactions" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_transactions_money_agent_transactions_cust_37e6962e" ON public."money_agent_transactions" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "money_agent_transactions_money_agent_transactions_serv_1ea72d5d" ON public."money_agent_transactions" ("service_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_controlled_medicine_register_phm_controlled_medici_92084ac9" ON public."phm_controlled_medicine_register" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_insurance_claims_phm_insurance_claims_company_id_f_b573ab66" ON public."phm_insurance_claims" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_purchase_order_items_phm_purchase_order_items_comp_ae4d0ec6" ON public."phm_purchase_order_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_purchase_orders_phm_purchase_orders_company_id_fke_f3d53b19" ON public."phm_purchase_orders" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_return_items_phm_return_items_company_id_fkey_fk_i_9224343b" ON public."phm_return_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_returns_phm_returns_company_id_fkey_fk_idx_4d73ab06" ON public."phm_returns" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_sale_items_phm_sale_items_company_id_fkey_fk_idx_98baba97" ON public."phm_sale_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_stock_adjustments_phm_stock_adjustments_company_id_994a87d6" ON public."phm_stock_adjustments" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_stock_receipts_phm_stock_receipts_company_id_fkey__41ad6ec8" ON public."phm_stock_receipts" ("company_id");

-- WAVE 20: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "phm_stock_transfers_phm_stock_transfers_company_id_fke_7987a4f7" ON public."phm_stock_transfers" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_agents_property_agents_profile_id_fkey_fk_idx_a2990f9e" ON public."property_agents" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_applications_property_applications_agent_id_f_6ac6c52d" ON public."property_applications" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_applications_property_applications_tenant_id__68be9e61" ON public."property_applications" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_applications_property_applications_unit_id_fk_0de1de3d" ON public."property_applications" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_approvals_property_approvals_company_id_fkey__294f0421" ON public."property_approvals" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_budgets_property_budgets_portfolio_id_fkey_fk_3582ff9b" ON public."property_budgets" ("portfolio_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_buildings_property_buildings_portfolio_id_fke_001f6f48" ON public."property_buildings" ("portfolio_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_expenses_property_expenses_property_id_fkey_f_926c9385" ON public."property_expenses" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_expenses_property_expenses_unit_id_fkey_fk_id_cccd8f5f" ON public."property_expenses" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_expenses_property_expenses_work_order_id_fkey_81a942f2" ON public."property_expenses" ("work_order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_handover_records_property_handover_records_co_ec442fab" ON public."property_handover_records" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_handover_records_property_handover_records_le_ef859610" ON public."property_handover_records" ("lease_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_inspection_items_property_inspection_items_co_4812691e" ON public."property_inspection_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_inspection_items_property_inspection_items_in_5c11fc84" ON public."property_inspection_items" ("inspection_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_inspections_property_inspections_company_id_f_c4bde3b5" ON public."property_inspections" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_inspections_property_inspections_lease_id_fke_6a8bb510" ON public."property_inspections" ("lease_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_insurances_property_insurances_property_id_fk_eeaf5bc8" ON public."property_insurances" ("property_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_insurances_property_insurances_unit_id_fkey_f_0096d798" ON public."property_insurances" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_integration_events_property_integration_event_c3198c1c" ON public."property_integration_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_invoice_lines_property_invoice_lines_company__d50a67b6" ON public."property_invoice_lines" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_invoice_lines_property_invoice_lines_invoice__644d0153" ON public."property_invoice_lines" ("invoice_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_invoices_property_invoices_lease_id_fkey_fk_i_c7f4db89" ON public."property_invoices" ("lease_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_invoices_property_invoices_tenant_id_fkey_fk__e30de4db" ON public."property_invoices" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_invoices_property_invoices_unit_id_fkey_fk_id_568a0590" ON public."property_invoices" ("unit_id");

-- WAVE 21: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_leases_property_leases_application_id_fkey_fk_cbc16279" ON public."property_leases" ("application_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_leases_property_leases_owner_id_fkey_fk_idx_58ea8751" ON public."property_leases" ("owner_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_leases_property_leases_tenant_id_fkey_fk_idx_b3c59b4c" ON public."property_leases" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_leases_property_leases_unit_id_fkey_fk_idx_62e2c4b9" ON public."property_leases" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_ledger_entries_property_ledger_entries_compan_ea0548a4" ON public."property_ledger_entries" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_listings_property_listings_agent_fk_fk_idx_ae891b61" ON public."property_listings" ("agent_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_listings_property_listings_company_id_fkey_fk_f19cc8f9" ON public."property_listings" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_listings_property_listings_unit_id_fkey_fk_id_af8eae11" ON public."property_listings" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_maintenance_requests_property_maintenance_req_3f3e2c8a" ON public."property_maintenance_requests" ("lease_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_maintenance_requests_property_maintenance_req_8834601c" ON public."property_maintenance_requests" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_maintenance_requests_property_maintenance_req_0cb867e1" ON public."property_maintenance_requests" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_meter_readings_property_meter_readings_meter__f98638d6" ON public."property_meter_readings" ("meter_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_notices_property_notices_company_id_fkey_fk_i_d2eb748e" ON public."property_notices" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_notices_property_notices_lease_id_fkey_fk_idx_917e6afa" ON public."property_notices" ("lease_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_notices_property_notices_tenant_id_fkey_fk_id_609eac54" ON public."property_notices" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_notifications_property_notifications_notice_i_9bc43ad0" ON public."property_notifications" ("notice_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_notifications_property_notifications_recipien_8a8502e3" ON public."property_notifications" ("recipient_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_notifications_property_notifications_tenant_i_df3a7f74" ON public."property_notifications" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_owners_property_owners_profile_id_fkey_fk_idx_82e6e673" ON public."property_owners" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_payments_property_payments_invoice_id_fkey_fk_bde7c4ba" ON public."property_payments" ("invoice_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_payments_property_payments_tenant_id_fkey_fk__d607d7cf" ON public."property_payments" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_plots_property_plots_owner_id_fkey_fk_idx_785a80b1" ON public."property_plots" ("owner_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_plots_property_plots_portfolio_id_fkey_fk_idx_a3d0e818" ON public."property_plots" ("portfolio_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_receipts_property_receipts_payment_id_fkey_fk_f84f1a1b" ON public."property_receipts" ("payment_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_reconciliations_property_reconciliations_comp_cca6f816" ON public."property_reconciliations" ("company_id");

-- WAVE 22: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_reconciliations_property_reconciliations_invo_cd2e100f" ON public."property_reconciliations" ("invoice_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_reconciliations_property_reconciliations_paym_280ffbd1" ON public."property_reconciliations" ("payment_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_rent_schedules_property_rent_schedules_lease__754bc585" ON public."property_rent_schedules" ("lease_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_service_charges_property_service_charges_comp_e69e9dea" ON public."property_service_charges" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_service_charges_property_service_charges_unit_def0ea0e" ON public."property_service_charges" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_tenant_documents_property_tenant_documents_co_4c29bde0" ON public."property_tenant_documents" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_tenant_documents_property_tenant_documents_te_c721cdd0" ON public."property_tenant_documents" ("tenant_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_tenants_property_tenants_profile_id_fkey_fk_i_5c7d763c" ON public."property_tenants" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_units_property_units_building_id_fkey_fk_idx_8e17b7ef" ON public."property_units" ("building_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_units_property_units_owner_id_fkey_fk_idx_ece8f3d2" ON public."property_units" ("owner_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_units_property_units_plot_id_fkey_fk_idx_d568c4b7" ON public."property_units" ("plot_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_utility_meters_property_utility_meters_unit_i_98d8995d" ON public."property_utility_meters" ("unit_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_work_orders_property_work_orders_assigned_pro_77297314" ON public."property_work_orders" ("assigned_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_work_orders_property_work_orders_contractor_i_35a034f7" ON public."property_work_orders" ("contractor_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "property_work_orders_property_work_orders_request_id_f_6d419877" ON public."property_work_orders" ("request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_alerts_restaurant_alerts_outlet_id_fkey_fk__b23a4968" ON public."restaurant_alerts" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_audit_events_restaurant_audit_events_compan_b76c8a0a" ON public."restaurant_audit_events" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_audit_events_restaurant_audit_events_outlet_f1812c8b" ON public."restaurant_audit_events" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_bill_splits_restaurant_bill_splits_company__a3589ec6" ON public."restaurant_bill_splits" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_bill_splits_restaurant_bill_splits_split_or_297ba5e9" ON public."restaurant_bill_splits" ("split_order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_combo_items_restaurant_combo_items_child_me_ce77c16b" ON public."restaurant_combo_items" ("child_menu_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_combo_items_restaurant_combo_items_company__d7255651" ON public."restaurant_combo_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_customers_restaurant_customers_guest_id_fke_0e3f9d0a" ON public."restaurant_customers" ("guest_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_dining_areas_restaurant_dining_areas_compan_5d3dcf43" ON public."restaurant_dining_areas" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_kitchen_tickets_restaurant_kitchen_tickets__1e4b5a03" ON public."restaurant_kitchen_tickets" ("order_id");

-- WAVE 23: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_kitchen_tickets_restaurant_kitchen_tickets__21e779ee" ON public."restaurant_kitchen_tickets" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_menu_categories_restaurant_menu_categories__ffcfd8b5" ON public."restaurant_menu_categories" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_modifier_groups_restaurant_modifier_groups__37a99069" ON public."restaurant_modifier_groups" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_modifier_options_restaurant_modifier_option_fa1417ab" ON public."restaurant_modifier_options" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_modifier_options_restaurant_modifier_option_7b446db2" ON public."restaurant_modifier_options" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_order_lines_restaurant_order_lines_company__5e112904" ON public."restaurant_order_lines" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_order_lines_restaurant_order_lines_menu_ite_019afd97" ON public."restaurant_order_lines" ("menu_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_order_lines_restaurant_order_lines_order_id_14d73109" ON public."restaurant_order_lines" ("order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_payments_restaurant_payments_company_id_fke_ce38f137" ON public."restaurant_payments" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_payments_restaurant_payments_order_id_fkey__97ffee85" ON public."restaurant_payments" ("order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_promotions_restaurant_promotions_outlet_id__b9b92a81" ON public."restaurant_promotions" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_purchase_lines_restaurant_purchase_lines_co_64f04406" ON public."restaurant_purchase_lines" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_purchase_lines_restaurant_purchase_lines_in_44b76729" ON public."restaurant_purchase_lines" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_purchase_lines_restaurant_purchase_lines_re_613d3ee5" ON public."restaurant_purchase_lines" ("request_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_purchase_requests_restaurant_purchase_reque_1e574530" ON public."restaurant_purchase_requests" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_purchase_requests_restaurant_purchase_reque_2ea5b3f6" ON public."restaurant_purchase_requests" ("supplier_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_recipe_ingredients_restaurant_recipe_ingred_d0aab033" ON public."restaurant_recipe_ingredients" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_recipe_ingredients_restaurant_recipe_ingred_92ec456b" ON public."restaurant_recipe_ingredients" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_refunds_restaurant_refunds_order_id_fkey_fk_e196fddb" ON public."restaurant_refunds" ("order_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_refunds_restaurant_refunds_payment_id_fkey__e4f3c148" ON public."restaurant_refunds" ("payment_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_reservations_restaurant_reservations_custom_177d4ec1" ON public."restaurant_reservations" ("customer_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_reservations_restaurant_reservations_outlet_1a0e5270" ON public."restaurant_reservations" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_reservations_restaurant_reservations_table__990e36df" ON public."restaurant_reservations" ("table_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_shifts_restaurant_shifts_company_id_fkey_fk_1ca4e8c7" ON public."restaurant_shifts" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_shifts_restaurant_shifts_employee_id_fkey_f_bc5cc22d" ON public."restaurant_shifts" ("employee_id");

-- WAVE 24: 25 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_shifts_restaurant_shifts_outlet_id_fkey_fk__fa0140a7" ON public."restaurant_shifts" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_staff_roles_restaurant_staff_roles_company__d02cdf7a" ON public."restaurant_staff_roles" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_staff_roles_restaurant_staff_roles_employee_40c204b1" ON public."restaurant_staff_roles" ("employee_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_wastage_restaurant_wastage_company_id_fkey__ac607e1f" ON public."restaurant_wastage" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_wastage_restaurant_wastage_inventory_item_i_411e3ad0" ON public."restaurant_wastage" ("inventory_item_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "restaurant_wastage_restaurant_wastage_outlet_id_fkey_f_87ae7a61" ON public."restaurant_wastage" ("outlet_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_order_return_items_sales_order_return_items_head_a777f41e" ON public."sales_order_return_items" ("return_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_order_returns_sales_order_returns_header_fkey_fk_1b72b004" ON public."sales_order_returns" ("order_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sales_quotation_items_sales_quotation_items_header_fke_505fdb0e" ON public."sales_quotation_items" ("quotation_id", "company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_announcements_sch_announcements_company_id_fkey_fk_296902f8" ON public."sch_announcements" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_assignment_submissions_sch_assignment_submissions__67418543" ON public."sch_assignment_submissions" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_disciplinary_records_sch_disciplinary_records_comp_6dd1c492" ON public."sch_disciplinary_records" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_documents_sch_documents_company_id_fkey_fk_idx_6efc2232" ON public."sch_documents" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_fee_invoice_lines_sch_fee_invoice_lines_company_id_f29d0ef2" ON public."sch_fee_invoice_lines" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_fee_structures_sch_fee_structures_company_id_fkey__cc61360d" ON public."sch_fee_structures" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_grading_scales_sch_grading_scales_company_id_fkey__c2f0fe58" ON public."sch_grading_scales" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_guardians_sch_guardians_company_id_fkey_fk_idx_743eefd8" ON public."sch_guardians" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_hostel_allocations_sch_hostel_allocations_company__93bdd763" ON public."sch_hostel_allocations" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_hostels_sch_hostels_company_id_fkey_fk_idx_b4aff4b0" ON public."sch_hostels" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_inventory_items_sch_inventory_items_company_id_fke_ddb7f4ab" ON public."sch_inventory_items" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_inventory_movements_sch_inventory_movements_compan_83dc347d" ON public."sch_inventory_movements" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_messages_sch_messages_company_id_fkey_fk_idx_cdbddfdb" ON public."sch_messages" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_scholarships_sch_scholarships_company_id_fkey_fk_i_8bd03be9" ON public."sch_scholarships" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sch_transport_assignments_sch_transport_assignments_co_c00b7838" ON public."sch_transport_assignments" ("company_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "subscription_notifications_subscription_notifications__73628b49" ON public."subscription_notifications" ("subscription_id");

-- WAVE 25: 16 index statements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_agents_support_agents_profile_id_fkey_fk_idx_44a5d18e" ON public."support_agents" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_agents_support_agents_team_id_fkey_fk_idx_c7707da7" ON public."support_agents" ("team_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_message_templates_support_message_templates_cr_f63f7ada" ON public."support_message_templates" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_team_members_support_team_members_profile_id_f_cd4a1358" ON public."support_team_members" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_team_members_support_team_members_team_id_fkey_6d3b1d87" ON public."support_team_members" ("team_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_teams_support_teams_created_by_fkey_fk_idx_086a0583" ON public."support_teams" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_ticket_activity_support_ticket_activity_actor__44e2a566" ON public."support_ticket_activity" ("actor_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_ticket_activity_support_ticket_activity_ticket_67ec50f6" ON public."support_ticket_activity" ("ticket_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_ticket_notes_support_ticket_notes_author_profi_956e7d31" ON public."support_ticket_notes" ("author_profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "support_ticket_notes_support_ticket_notes_ticket_id_fk_21003979" ON public."support_ticket_notes" ("ticket_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "user_table_preferences_user_table_preferences_user_id__0940a0e2" ON public."user_table_preferences" ("user_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "whatsapp_account_links_whatsapp_account_links_created__694c9be8" ON public."whatsapp_account_links" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "whatsapp_account_links_whatsapp_account_links_profile__a0996ae5" ON public."whatsapp_account_links" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "whatsapp_accounts_whatsapp_accounts_created_by_fkey_fk_73ec9fdc" ON public."whatsapp_accounts" ("created_by");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "whatsapp_contacts_whatsapp_contacts_profile_id_fkey_fk_091c387a" ON public."whatsapp_contacts" ("profile_id");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "whatsapp_conversations_whatsapp_conversations_company__532015cd" ON public."whatsapp_conversations" ("company_id");

