export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  supabaseUrl: process.env.VITE_SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.VITE_SUPABASE_ANON_KEY ?? "",
  supabaseSecretKey: process.env.SUPABASE_SECRET_KEY ?? "",
  healthcareSmsProvider: process.env.HEALTHCARE_SMS_PROVIDER ?? "",
  healthcareSmsProviderUrl: process.env.HEALTHCARE_SMS_PROVIDER_URL ?? "",
  healthcareSmsProviderApiKey: process.env.HEALTHCARE_SMS_PROVIDER_API_KEY ?? "",
  healthcareSmsWebhookSecret: process.env.HEALTHCARE_SMS_WEBHOOK_SECRET ?? "",
};
