import { TRPCError } from "@trpc/server";
import type { CreateExpressContextOptions } from "@trpc/server/adapters/express";
import { z } from "zod";
import { ENV } from "./_core/env";
import { resolveVerifiedProfile } from "./aiApprovals";
import { storagePut } from "./storage";

export const SCHOOL_TABLES = [
  "sch_academic_years", "sch_terms", "sch_departments", "sch_subjects", "sch_streams", "sch_grading_scales", "sch_timetables",
  "sch_admissions", "sch_students", "sch_guardians", "sch_student_guardians", "sch_enrollments", "sch_documents", "sch_teachers", "sch_teacher_assignments",
  "sch_classes", "sch_attendance_sessions", "sch_attendance_records", "sch_exams", "sch_assessments", "sch_assessment_scores", "sch_report_cards", "sch_assignments", "sch_assignment_submissions",
  "sch_fees", "sch_fee_structures", "sch_fee_invoices", "sch_fee_invoice_lines", "sch_payments", "sch_scholarships",
  "sch_transport", "sch_transport_assignments", "sch_hostels", "sch_hostel_allocations", "sch_books", "sch_library_loans", "sch_inventory_items", "sch_inventory_movements",
  "sch_disciplinary_records", "sch_announcements", "sch_messages", "sch_portal_links", "sch_notifications", "sch_approval_requests", "sch_audit_logs",
] as const;

type SchoolTable = (typeof SCHOOL_TABLES)[number];
type SchoolRow = Record<string, any> & { id: string; name: string; status: string; amount: number | null; data: Record<string, any> };
type VerifiedProfile = { id: string; company_id: string; full_name: string | null; role: string };
const schoolTableSchema = z.enum(SCHOOL_TABLES);
const idSchema = z.string().uuid();
const text = z.string().trim().min(1).max(240);
const optionalText = z.string().trim().max(2_000).optional().default("");
const email = z.string().trim().email().max(320).or(z.literal("")).default("");
const money = z.number().finite().min(0).max(10_000_000_000);
const date = z.string().date();
const utc = z.string().datetime();
const now = () => new Date().toISOString();
const decimal = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;

const adminRoles = new Set(["Super Administrator", "Organization Owner", "CEO", "School Administrator", "Academic Director", "Principal"]);
const groupForRole: Record<string, readonly string[]> = {
  "School Administrator": ["admin", "academic", "admissions", "finance", "services", "welfare", "communications", "governance"],
  "Academic Director": ["academic", "admissions", "governance"], Principal: ["academic", "admissions", "governance"], "Deputy Principal": ["academic", "welfare"],
  "Academic Master": ["academic"], "Head of Department": ["academic", "teaching"], "Examination Officer": ["academic"], Registrar: ["academic", "admissions"],
  Teacher: ["teaching"], "Class Teacher": ["teaching"], "Admissions Officer": ["admissions"], Librarian: ["services"], "Transport Officer": ["services"], "Hostel Warden": ["services"], "Discipline Officer": ["welfare"],
  Bursar: ["finance"], Cashier: ["finance"], "Billing Officer": ["finance"], "Finance Manager": ["finance"], CFO: ["finance"],
  Parent: ["portal"], Guardian: ["portal"], Student: ["portal"],
};
type SchoolAction = "read" | "config" | "admissions" | "academic" | "teaching" | "finance" | "services" | "welfare" | "communications" | "governance" | "portal";
const permissions: Record<SchoolAction, readonly string[]> = {
  read: ["admin", "academic", "admissions", "teaching", "finance", "services", "welfare", "communications", "governance"],
  config: ["admin", "academic"], admissions: ["admin", "admissions", "academic"], academic: ["admin", "academic"], teaching: ["admin", "academic", "teaching"],
  finance: ["admin", "finance"], services: ["admin", "services"], welfare: ["admin", "welfare", "academic"], communications: ["admin", "academic", "teaching", "admissions", "finance", "services", "welfare"], governance: ["admin", "governance"], portal: ["portal"],
};

export function schoolAccessForRole(role: string) {
  const groups = groupForRole[role] ?? [];
  const can = (action: SchoolAction) => adminRoles.has(role) || permissions[action].some((group) => groups.includes(group));
  return {
    role, canRead: can("read"), canConfigure: can("config"), canManageAdmissions: can("admissions"), canManageAcademic: can("academic"),
    canTeach: can("teaching"), canManageFinance: can("finance"), canManageServices: can("services"), canManageWelfare: can("welfare"),
    canCommunicate: can("communications"), canGovern: can("governance"), canUsePortal: can("portal"),
  };
}

function ensure(role: string, action: SchoolAction) {
  const access = schoolAccessForRole(role);
  const allowed: Record<SchoolAction, boolean> = {
    read: access.canRead, config: access.canConfigure, admissions: access.canManageAdmissions, academic: access.canManageAcademic, teaching: access.canTeach,
    finance: access.canManageFinance, services: access.canManageServices, welfare: access.canManageWelfare, communications: access.canCommunicate, governance: access.canGovern, portal: access.canUsePortal,
  };
  if (!allowed[action]) throw new TRPCError({ code: "FORBIDDEN", message: "Your assigned School Management role does not allow this action." });
  return access;
}

function endpoint(table: SchoolTable, query = new URLSearchParams()) { return `${ENV.supabaseUrl.replace(/\/$/, "")}/rest/v1/${table}?${query.toString()}`; }
async function request<T>(table: SchoolTable, token: string, query = new URLSearchParams(), init: RequestInit = {}) {
  if (!ENV.supabaseUrl || !ENV.supabaseAnonKey) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "School data services are not configured." });
  const response = await fetch(endpoint(table, query), { ...init, headers: { apikey: ENV.supabaseAnonKey, authorization: `Bearer ${token}`, "content-type": "application/json", ...(init.headers || {}) } });
  const body = await response.json().catch(() => null) as T | { message?: string; details?: string } | null;
  if (!response.ok) {
    if (response.status === 401) throw new TRPCError({ code: "UNAUTHORIZED", message: "Your workspace session could not be verified." });
    if (response.status === 403) throw new TRPCError({ code: "FORBIDDEN", message: "This School Management record is not available to your workspace." });
    if (response.status === 409) throw new TRPCError({ code: "CONFLICT", message: "A School Management record changed before your request completed. Refresh and try again." });
    throw new TRPCError({ code: "BAD_REQUEST", message: "The School Management record could not be saved. Check the required fields and try again." });
  }
  return body as T;
}
function rowData(row: Record<string, unknown>): SchoolRow { const data = row.data && typeof row.data === "object" && !Array.isArray(row.data) ? row.data as Record<string, any> : {}; return { ...data, ...row, data } as SchoolRow; }
function params(companyId: string, id?: string) { const value = new URLSearchParams({ select: "*", company_id: `eq.${companyId}` }); if (id) value.set("id", `eq.${id}`); return value; }
async function rows(table: SchoolTable, token: string, companyId: string, limit = 250): Promise<SchoolRow[]> { const query = params(companyId); query.set("order", "created_at.desc"); query.set("limit", String(limit)); return (await request<Record<string, unknown>[]>(table, token, query)).map(rowData); }
async function row(table: SchoolTable, token: string, companyId: string, id: string): Promise<SchoolRow> { const query = params(companyId, id); query.set("limit", "1"); const record = (await request<Record<string, unknown>[]>(table, token, query))[0]; if (!record) throw new TRPCError({ code: "NOT_FOUND", message: "The selected School Management record is unavailable in this workspace." }); return rowData(record); }
async function insert(table: SchoolTable, token: string, companyId: string, record: { name: string; status: string; amount?: number | null; notes?: string | null; data?: Record<string, unknown> }) {
  const payload = { company_id: companyId, name: record.name, status: record.status, amount: record.amount ?? null, notes: record.notes ?? null, data: record.data ?? {} };
  const created = (await request<Record<string, unknown>[]>(table, token, new URLSearchParams(), { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }))[0];
  if (!created) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "The School Management change could not be confirmed." });
  return rowData(created);
}
async function update(table: SchoolTable, token: string, companyId: string, id: string, patch: { name?: string; status?: string; amount?: number | null; notes?: string | null; data?: Record<string, unknown> }) {
  const prior = await row(table, token, companyId, id); const query = params(companyId, id);
  const payload = { ...(patch.name === undefined ? {} : { name: patch.name }), ...(patch.status === undefined ? {} : { status: patch.status }), ...(patch.amount === undefined ? {} : { amount: patch.amount }), ...(patch.notes === undefined ? {} : { notes: patch.notes }), ...(patch.data === undefined ? {} : { data: { ...prior.data, ...patch.data } }) };
  const changed = (await request<Record<string, unknown>[]>(table, token, query, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }))[0];
  if (!changed) throw new TRPCError({ code: "NOT_FOUND", message: "The selected School Management record is unavailable in this workspace." }); return rowData(changed);
}
async function audit(token: string, companyId: string, actor: VerifiedProfile, action: string, entity: string, recordId: string, details = "") { return insert("sch_audit_logs", token, companyId, { name: action, status: "Recorded", notes: details || null, data: { action, entity, recordId, actorId: actor.id, actorName: actor.full_name || "Workspace user", recordedAt: now() } }); }
async function notify(token: string, companyId: string, name: string, severity: "Info" | "Warning" | "Critical", data: Record<string, unknown>) { return insert("sch_notifications", token, companyId, { name, status: "Unread", data: { severity, ...data, createdAt: now() } }); }
async function context(req: CreateExpressContextOptions["req"], action: SchoolAction) { const { profile, token } = await resolveVerifiedProfile(req); return { profile: profile as VerifiedProfile, token, access: ensure(profile.role, action) }; }
async function dashboardContext(req: CreateExpressContextOptions["req"]) { const { profile, token } = await resolveVerifiedProfile(req); const access = schoolAccessForRole(profile.role); if (!access.canRead && !access.canUsePortal) throw new TRPCError({ code: "FORBIDDEN", message: "Your assigned role cannot open School Management." }); return { profile: profile as VerifiedProfile, token, access }; }
function searchable(records: SchoolRow[], search?: string) { const needle = search?.toLocaleLowerCase(); return needle ? records.filter((record) => JSON.stringify(record).toLocaleLowerCase().includes(needle)) : records; }
async function mayOperateTeacherAssignment(profile: VerifiedProfile, token: string, companyId: string, assignment: SchoolRow) {
  if (adminRoles.has(profile.role) || schoolAccessForRole(profile.role).canManageAcademic) return true;
  const linkedTeacherIds = (await rows("sch_portal_links", token, companyId, 1_000))
    .filter((link) => link.profileId === profile.id && link.scope === "Teacher" && link.status === "Active")
    .map((link) => String(link.recordId));
  return linkedTeacherIds.includes(String(assignment.teacherId));
}
function recordAction(table: SchoolTable): SchoolAction {
  if (["sch_academic_years", "sch_terms", "sch_departments", "sch_subjects", "sch_streams", "sch_grading_scales"].includes(table)) return "config";
  if (["sch_admissions", "sch_students", "sch_guardians", "sch_student_guardians", "sch_enrollments"].includes(table)) return "admissions";
  if (["sch_classes", "sch_timetables", "sch_exams", "sch_assessments", "sch_assessment_scores", "sch_report_cards"].includes(table)) return "academic";
  if (["sch_attendance_sessions", "sch_attendance_records", "sch_assignments", "sch_assignment_submissions", "sch_teacher_assignments"].includes(table)) return "teaching";
  if (["sch_fees", "sch_fee_structures", "sch_fee_invoices", "sch_fee_invoice_lines", "sch_payments", "sch_scholarships"].includes(table)) return "finance";
  if (["sch_transport", "sch_transport_assignments", "sch_hostels", "sch_hostel_allocations", "sch_books", "sch_library_loans", "sch_inventory_items", "sch_inventory_movements"].includes(table)) return "services";
  if (["sch_disciplinary_records"].includes(table)) return "welfare";
  if (["sch_announcements", "sch_messages", "sch_notifications"].includes(table)) return "communications";
  return "governance";
}

export const schoolListInput = z.object({ table: schoolTableSchema, search: z.string().trim().max(120).optional(), limit: z.number().int().min(1).max(500).default(250) });
export const schoolIdInput = z.object({ id: idSchema });
export const schoolArchiveInput = z.object({ table: schoolTableSchema, id: idSchema, reason: optionalText });
const namedRecord = z.object({ name: text, notes: optionalText });
export const schoolAcademicYearInput = namedRecord.extend({ startDate: date, endDate: date, active: z.boolean().default(false) });
export const schoolTermInput = namedRecord.extend({ academicYearId: idSchema, startDate: date, endDate: date, active: z.boolean().default(false) });
export const schoolDepartmentInput = namedRecord.extend({ headTeacherId: idSchema.optional() });
export const schoolSubjectInput = namedRecord.extend({ code: z.string().trim().max(30).optional().default(""), departmentId: idSchema.optional(), compulsory: z.boolean().default(false) });
export const schoolClassInput = namedRecord.extend({ academicYearId: idSchema, level: text, capacity: z.number().int().min(1).max(5_000), classTeacherId: idSchema.optional() });
export const schoolStreamInput = namedRecord.extend({ classId: idSchema, capacity: z.number().int().min(1).max(5_000), classTeacherId: idSchema.optional() });
export const schoolGradingScaleInput = namedRecord.extend({ bands: z.array(z.object({ grade: z.string().trim().min(1).max(10), min: z.number().min(0).max(100), max: z.number().min(0).max(100), points: z.number().min(0).max(20), remark: z.string().trim().max(100).optional().default("") })).min(1).max(20), active: z.boolean().default(false) });
export const schoolAdmissionInput = z.object({ studentName: text, gender: z.enum(["Female", "Male", "Other", "Prefer not to say"]), dateOfBirth: date, guardianName: text, guardianPhone: z.string().trim().min(7).max(40), guardianEmail: email, relationship: text, academicYearId: idSchema, classId: idSchema, streamId: idSchema.optional(), notes: optionalText });
export const schoolAdmissionDecisionInput = z.object({ admissionId: idSchema, decision: z.enum(["Approved", "Rejected", "Waitlisted"]), decisionNotes: optionalText });
export const schoolTeacherInput = namedRecord.extend({ employeeId: idSchema.optional(), email, phone: z.string().trim().max(40).optional().default(""), departmentId: idSchema.optional(), qualification: optionalText });
export const schoolTeacherAssignmentInput = z.object({ teacherId: idSchema, classId: idSchema, subjectId: idSchema, termId: idSchema, role: z.enum(["Subject Teacher", "Class Teacher", "Examiner"]).default("Subject Teacher"), notes: optionalText });
export const schoolTimetableInput = z.object({ termId: idSchema, classId: idSchema, subjectId: idSchema, teacherAssignmentId: idSchema, weekday: z.enum(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]), startsAt: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), endsAt: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), room: optionalText });
export const schoolAttendanceSessionInput = z.object({ classId: idSchema, termId: idSchema, attendanceDate: date, notes: optionalText });
export const schoolAttendanceInput = z.object({ sessionId: idSchema, records: z.array(z.object({ studentId: idSchema, status: z.enum(["Present", "Absent", "Late", "Excused"]), reason: optionalText })).min(1).max(1_000) });
export const schoolAssessmentInput = z.object({ name: text, termId: idSchema, classId: idSchema, subjectId: idSchema, teacherAssignmentId: idSchema, assessmentDate: date, maxScore: z.number().finite().positive().max(1_000), weight: z.number().finite().min(0).max(100).default(100), notes: optionalText });
export const schoolScoreInput = z.object({ assessmentId: idSchema, scores: z.array(z.object({ studentId: idSchema, score: z.number().finite().min(0).max(1_000), remarks: optionalText })).min(1).max(1_000) });
export const schoolReportCardInput = z.object({ studentId: idSchema, termId: idSchema, gradingScaleId: idSchema, notes: optionalText, publish: z.boolean().default(false) });
export const schoolAssignmentInput = z.object({ name: text, classId: idSchema, subjectId: idSchema, teacherAssignmentId: idSchema, dueAt: utc, instructions: optionalText, maximumScore: z.number().finite().positive().max(1_000).default(100) });
export const schoolAssignmentSubmissionInput = z.object({ assignmentId: idSchema, studentId: idSchema, documentId: idSchema.optional(), notes: optionalText });
export const schoolFeeStructureInput = z.object({ name: text, termId: idSchema, classId: idSchema.optional(), amount: money, mandatory: z.boolean().default(true), notes: optionalText });
export const schoolInvoiceInput = z.object({ studentId: idSchema, termId: idSchema, feeStructureIds: z.array(idSchema).min(1).max(100), dueDate: date, notes: optionalText });
export const schoolPaymentInput = z.object({ invoiceId: idSchema, amount: money.refine((value) => value > 0, "Enter a payment amount greater than zero."), method: z.enum(["Cash", "Mobile money", "Bank transfer", "Card", "Cheque", "Scholarship"]), reference: optionalText, notes: optionalText });
export const schoolScholarshipInput = z.object({ studentId: idSchema, termId: idSchema, amount: money.refine((value) => value > 0, "Enter a scholarship amount greater than zero."), reason: text });
export const schoolScholarshipDecisionInput = z.object({ scholarshipId: idSchema, decision: z.enum(["Approved", "Rejected"]), notes: optionalText });
export const schoolServiceInput = z.object({ table: z.enum(["sch_transport", "sch_hostels", "sch_books", "sch_inventory_items"]), name: text, amount: money.optional(), notes: optionalText, data: z.record(z.string(), z.unknown()).default({}) });
export const schoolServiceAssignmentInput = z.object({ table: z.enum(["sch_transport_assignments", "sch_hostel_allocations"]), studentId: idSchema, serviceId: idSchema, termId: idSchema.optional(), notes: optionalText });
export const schoolLibraryLoanInput = z.object({ bookId: idSchema, studentId: idSchema, dueDate: date, notes: optionalText });
export const schoolInventoryMovementInput = z.object({ itemId: idSchema, quantityDelta: z.number().finite().refine((value) => value !== 0, "Enter a non-zero movement quantity."), reason: text, notes: optionalText });
export const schoolDisciplineInput = z.object({ studentId: idSchema, incidentDate: date, category: text, severity: z.enum(["Low", "Medium", "High", "Critical"]), description: text, actionTaken: optionalText });
export const schoolAnnouncementInput = z.object({ title: text, body: text.max(10_000), audience: z.enum(["All", "Students", "Parents", "Teachers", "Staff", "Class"]), classId: idSchema.optional(), publishedAt: utc.optional() });
export const schoolMessageInput = z.object({ recipientProfileId: idSchema.optional(), recipientType: z.enum(["Parent", "Student", "Teacher", "Staff", "Class"]), classId: idSchema.optional(), subject: text, body: text.max(10_000) });
export const schoolPortalLinkInput = z.object({ profileId: idSchema, scope: z.enum(["Parent", "Student", "Teacher"]), recordId: idSchema, notes: optionalText });
export const schoolDocumentInput = z.object({ ownerType: z.enum(["Admission", "Student", "Guardian", "Assignment", "Discipline", "Report card"]), ownerId: idSchema, storageKey: text.max(500), fileName: text.max(300), mimeType: text.max(120), access: z.enum(["Restricted", "Portal visible"]).default("Restricted") });
export const schoolDocumentUploadInput = z.object({ ownerType: z.enum(["Admission", "Student", "Guardian", "Assignment", "Discipline", "Report card"]), ownerId: idSchema, fileName: text.max(300), mimeType: z.enum(["application/pdf", "image/jpeg", "image/png", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/csv"]), access: z.enum(["Restricted", "Portal visible"]).default("Restricted"), base64: z.string().min(4).max(8_500_000) });
export const schoolApprovalRequestInput = z.object({ subject: text, requestType: z.enum(["Admission", "Scholarship", "Report card correction", "Discipline", "Fee waiver"]), recordId: idSchema, rationale: text.max(2_000) });
export const schoolApprovalDecisionInput = z.object({ approvalId: idSchema, decision: z.enum(["Approved", "Rejected"]), decisionNotes: optionalText });

export async function getSchoolAccess(req: CreateExpressContextOptions["req"]) { const { profile } = await resolveVerifiedProfile(req); return schoolAccessForRole(profile.role); }
export async function listSchoolRecords(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolListInput>) { const { profile, token } = await context(req, recordAction(input.table)); return { access: schoolAccessForRole(profile.role), records: searchable(await rows(input.table, token, profile.company_id, input.limit), input.search) }; }
export async function archiveSchoolRecord(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolArchiveInput>) { const { profile, token } = await context(req, recordAction(input.table)); const record = await row(input.table, token, profile.company_id, input.id); if (["sch_students", "sch_teachers"].includes(input.table) && record.status === "Active") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Deactivate this active school profile through its authorised workflow before archiving it." }); const archived = await update(input.table, token, profile.company_id, input.id, { status: "Archived", data: { archivedAt: now(), archiveReason: input.reason || "Archived by authorised school user" } }); await audit(token, profile.company_id, profile, "School record archived", input.table, archived.id, input.reason); return archived; }

async function createConfiguredRecord(req: CreateExpressContextOptions["req"], action: SchoolAction, table: SchoolTable, name: string, data: Record<string, unknown>, notes: string, amount: number | null = null, status = "Active") { const { profile, token } = await context(req, action); const created = await insert(table, token, profile.company_id, { name, status, amount, notes: notes || null, data: { ...data, createdAt: now() } }); await audit(token, profile.company_id, profile, `${table} created`, table, created.id); return created; }
export async function createSchoolAcademicYear(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAcademicYearInput>) { if (input.endDate <= input.startDate) throw new TRPCError({ code: "BAD_REQUEST", message: "Academic year end date must be after its start date." }); const created = await createConfiguredRecord(req, "config", "sch_academic_years", input.name, input, input.notes, null, input.active ? "Active" : "Draft"); if (input.active) { const { profile, token } = await context(req, "config"); for (const record of (await rows("sch_academic_years", token, profile.company_id)).filter((record) => record.id !== created.id && record.status === "Active")) await update("sch_academic_years", token, profile.company_id, record.id, { status: "Closed", data: { closedAt: now(), closedByActivation: created.id } }); } return created; }
export async function createSchoolTerm(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolTermInput>) { if (input.endDate <= input.startDate) throw new TRPCError({ code: "BAD_REQUEST", message: "Term end date must be after its start date." }); const { profile, token } = await context(req, "config"); const year = await row("sch_academic_years", token, profile.company_id, input.academicYearId); if (year.status === "Archived") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "An archived academic year cannot receive a term." }); return createConfiguredRecord(req, "config", "sch_terms", input.name, input, input.notes, null, input.active ? "Active" : "Draft"); }
export async function createSchoolDepartment(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolDepartmentInput>) { return createConfiguredRecord(req, "config", "sch_departments", input.name, input, input.notes); }
export async function createSchoolSubject(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolSubjectInput>) { const { profile, token } = await context(req, "config"); if (input.departmentId) await row("sch_departments", token, profile.company_id, input.departmentId); return createConfiguredRecord(req, "config", "sch_subjects", input.name, input, input.notes); }
export async function createSchoolClass(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolClassInput>) { const { profile, token } = await context(req, "config"); await row("sch_academic_years", token, profile.company_id, input.academicYearId); if (input.classTeacherId) await row("sch_teachers", token, profile.company_id, input.classTeacherId); return createConfiguredRecord(req, "config", "sch_classes", input.name, input, input.notes); }
export async function createSchoolStream(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolStreamInput>) { const { profile, token } = await context(req, "config"); await row("sch_classes", token, profile.company_id, input.classId); if (input.classTeacherId) await row("sch_teachers", token, profile.company_id, input.classTeacherId); return createConfiguredRecord(req, "config", "sch_streams", input.name, input, input.notes); }
export async function createSchoolGradingScale(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolGradingScaleInput>) { const sorted = [...input.bands].sort((a, b) => a.min - b.min); if (sorted.some((band) => band.min > band.max) || sorted.some((band, index) => index && band.min <= sorted[index - 1].max)) throw new TRPCError({ code: "BAD_REQUEST", message: "Grade bands must be non-overlapping ranges with valid minimum and maximum scores." }); return createConfiguredRecord(req, "config", "sch_grading_scales", input.name, { ...input, bands: sorted }, input.notes, null, input.active ? "Active" : "Draft"); }

export async function createSchoolTeacher(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolTeacherInput>) { const { profile, token } = await context(req, "academic"); if (input.departmentId) await row("sch_departments", token, profile.company_id, input.departmentId); return createConfiguredRecord(req, "academic", "sch_teachers", input.name, input, input.notes); }
export async function createSchoolAdmission(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAdmissionInput>) { const { profile, token } = await context(req, "admissions"); await Promise.all([row("sch_academic_years", token, profile.company_id, input.academicYearId), row("sch_classes", token, profile.company_id, input.classId), ...(input.streamId ? [row("sch_streams", token, profile.company_id, input.streamId)] : [])]); const admissionNo = `APP-${new Date().getUTCFullYear()}-${Date.now().toString().slice(-8)}`; const admission = await insert("sch_admissions", token, profile.company_id, { name: input.studentName, status: "Submitted", notes: input.notes || null, data: { ...input, admissionNo, submittedAt: now() } }); await audit(token, profile.company_id, profile, "Student admission submitted", "sch_admissions", admission.id); return admission; }
export async function decideSchoolAdmission(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAdmissionDecisionInput>) { const { profile, token } = await context(req, "admissions"); const admission = await row("sch_admissions", token, profile.company_id, input.admissionId); if (admission.status !== "Submitted" && admission.status !== "Waitlisted") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Only submitted or waitlisted admissions may be decided." }); if (input.decision !== "Approved") { const decided = await update("sch_admissions", token, profile.company_id, admission.id, { status: input.decision, data: { decidedAt: now(), decidedBy: profile.id, decisionNotes: input.decisionNotes } }); await audit(token, profile.company_id, profile, `Admission ${input.decision.toLowerCase()}`, "sch_admissions", decided.id, input.decisionNotes); return { admission: decided, student: null, enrollment: null }; }
  const [year, schoolClass] = await Promise.all([row("sch_academic_years", token, profile.company_id, String(admission.academicYearId)), row("sch_classes", token, profile.company_id, String(admission.classId))]);
  if (year.status !== "Active") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Student admission can only be approved for an active academic year." });
  const activeEnrollments = (await rows("sch_enrollments", token, profile.company_id, 2_000)).filter((record) => record.classId === schoolClass.id && record.status === "Active"); if (activeEnrollments.length >= decimal(schoolClass.capacity)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "The selected class has reached its active enrollment capacity." });
  const guardian = await insert("sch_guardians", token, profile.company_id, { name: String(admission.guardianName), status: "Active", data: { phone: admission.guardianPhone, email: admission.guardianEmail, relationship: admission.relationship, createdFromAdmissionId: admission.id } });
  const admissionNo = `ADM-${new Date().getUTCFullYear()}-${String(activeEnrollments.length + 1).padStart(4, "0")}`;
  const student = await insert("sch_students", token, profile.company_id, { name: admission.name, status: "Active", data: { admissionNo, gender: admission.gender, dateOfBirth: admission.dateOfBirth, admissionId: admission.id, admittedAt: now() } });
  await insert("sch_student_guardians", token, profile.company_id, { name: `${student.name} · ${guardian.name}`, status: "Active", data: { studentId: student.id, guardianId: guardian.id, relationship: admission.relationship, primary: true } });
  const enrollment = await insert("sch_enrollments", token, profile.company_id, { name: `${student.name} · ${schoolClass.name}`, status: "Active", data: { studentId: student.id, studentName: student.name, academicYearId: year.id, classId: schoolClass.id, className: schoolClass.name, streamId: admission.streamId || null, enrolledAt: now() } });
  const decided = await update("sch_admissions", token, profile.company_id, admission.id, { status: "Approved", data: { decidedAt: now(), decidedBy: profile.id, decisionNotes: input.decisionNotes, studentId: student.id, enrollmentId: enrollment.id } }); await audit(token, profile.company_id, profile, "Admission approved and learner enrolled", "sch_admissions", admission.id); return { admission: decided, student, enrollment }; }

export async function createSchoolTeacherAssignment(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolTeacherAssignmentInput>) { const { profile, token } = await context(req, "academic"); const [teacher, schoolClass, subject, term] = await Promise.all([row("sch_teachers", token, profile.company_id, input.teacherId), row("sch_classes", token, profile.company_id, input.classId), row("sch_subjects", token, profile.company_id, input.subjectId), row("sch_terms", token, profile.company_id, input.termId)]); const assignment = await insert("sch_teacher_assignments", token, profile.company_id, { name: `${teacher.name} · ${subject.name} · ${schoolClass.name}`, status: "Active", notes: input.notes || null, data: { ...input, teacherName: teacher.name, className: schoolClass.name, subjectName: subject.name, termName: term.name, assignedAt: now() } }); await audit(token, profile.company_id, profile, "Teacher assignment created", "sch_teacher_assignments", assignment.id); return assignment; }
export async function createSchoolTimetable(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolTimetableInput>) { const { profile, token } = await context(req, "academic"); if (input.endsAt <= input.startsAt) throw new TRPCError({ code: "BAD_REQUEST", message: "A timetable period must end after it starts." }); const assignment = await row("sch_teacher_assignments", token, profile.company_id, input.teacherAssignmentId); if (assignment.classId !== input.classId || assignment.subjectId !== input.subjectId || assignment.termId !== input.termId) throw new TRPCError({ code: "FORBIDDEN", message: "The selected teacher assignment does not match this class, subject, and term." }); const conflicts = (await rows("sch_timetables", token, profile.company_id, 1_000)).filter((record) => record.status === "Scheduled" && record.termId === input.termId && record.weekday === input.weekday && record.classId === input.classId && input.startsAt < String(record.endsAt) && input.endsAt > String(record.startsAt)); if (conflicts.length) throw new TRPCError({ code: "CONFLICT", message: "This class already has a timetable period that overlaps the requested time." }); const timetable = await insert("sch_timetables", token, profile.company_id, { name: `${input.weekday} · ${assignment.className} · ${assignment.subjectName}`, status: "Scheduled", data: { ...input, teacherId: assignment.teacherId, createdAt: now() } }); await audit(token, profile.company_id, profile, "Timetable period scheduled", "sch_timetables", timetable.id); return timetable; }
export async function openSchoolAttendanceSession(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAttendanceSessionInput>) { const { profile, token, access } = await context(req, "teaching"); const schoolClass = await row("sch_classes", token, profile.company_id, input.classId); await row("sch_terms", token, profile.company_id, input.termId); if (!access.canManageAcademic && !adminRoles.has(profile.role)) { const assignments = (await rows("sch_teacher_assignments", token, profile.company_id, 1_000)).filter((record) => record.classId === input.classId && record.termId === input.termId && record.status === "Active"); const allowed = await Promise.all(assignments.map((assignment) => mayOperateTeacherAssignment(profile, token, profile.company_id, assignment))); if (!allowed.some(Boolean)) throw new TRPCError({ code: "FORBIDDEN", message: "Teachers may only open attendance for a class to which they are assigned." }); }
  const duplicate = (await rows("sch_attendance_sessions", token, profile.company_id, 1_000)).find((record) => record.classId === input.classId && record.attendanceDate === input.attendanceDate && record.status !== "Archived"); if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "Attendance has already been opened for this class and date." }); const session = await insert("sch_attendance_sessions", token, profile.company_id, { name: `${schoolClass.name} · ${input.attendanceDate}`, status: "Open", notes: input.notes || null, data: { ...input, openedBy: profile.id, openedAt: now() } }); await audit(token, profile.company_id, profile, "Attendance session opened", "sch_attendance_sessions", session.id); return session; }
export async function recordSchoolAttendance(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAttendanceInput>) { const { profile, token, access } = await context(req, "teaching"); const session = await row("sch_attendance_sessions", token, profile.company_id, input.sessionId); if (session.status === "Finalized") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "A finalized attendance session cannot be overwritten." }); if (!access.canManageAcademic && !adminRoles.has(profile.role)) { const assignments = (await rows("sch_teacher_assignments", token, profile.company_id, 1_000)).filter((record) => record.classId === session.classId && record.termId === session.termId && record.status === "Active"); const allowed = await Promise.all(assignments.map((assignment) => mayOperateTeacherAssignment(profile, token, profile.company_id, assignment))); if (!allowed.some(Boolean)) throw new TRPCError({ code: "FORBIDDEN", message: "Teachers may only record attendance for a class to which they are assigned." }); } const enrolled = new Set((await rows("sch_enrollments", token, profile.company_id, 2_000)).filter((record) => record.classId === session.classId && record.status === "Active").map((record) => record.studentId)); if (input.records.some((record) => !enrolled.has(record.studentId))) throw new TRPCError({ code: "FORBIDDEN", message: "Attendance records must belong to active learners in the selected class." }); const existing = await rows("sch_attendance_records", token, profile.company_id, 2_000); for (const record of input.records) { const prior = existing.find((item) => item.sessionId === session.id && item.studentId === record.studentId); if (prior) await update("sch_attendance_records", token, profile.company_id, prior.id, { status: record.status, notes: record.reason || null, data: { recordedBy: profile.id, correctedAt: now(), correctionReason: record.reason || "" } }); else await insert("sch_attendance_records", token, profile.company_id, { name: `${session.name} · ${record.studentId}`, status: record.status, notes: record.reason || null, data: { sessionId: session.id, studentId: record.studentId, recordedBy: profile.id, recordedAt: now() } }); }
  const finalized = await update("sch_attendance_sessions", token, profile.company_id, session.id, { status: "Finalized", data: { finalizedAt: now(), finalizedBy: profile.id, recordedCount: input.records.length } }); await audit(token, profile.company_id, profile, "Attendance session finalized", "sch_attendance_sessions", session.id); return finalized; }

function gradeFor(score: number, maxScore: number, bands: Array<{ grade: string; min: number; max: number; points: number; remark?: string }>) { const percent = maxScore <= 0 ? 0 : (score / maxScore) * 100; const band = bands.find((item) => percent >= item.min && percent <= item.max); return { percentage: percent, grade: band?.grade || "Ungraded", points: band?.points ?? 0, remark: band?.remark || "No matching grade band" }; }
export async function createSchoolAssessment(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAssessmentInput>) { const { profile, token } = await context(req, "teaching"); const assignment = await row("sch_teacher_assignments", token, profile.company_id, input.teacherAssignmentId); if (assignment.classId !== input.classId || assignment.subjectId !== input.subjectId || assignment.termId !== input.termId || !(await mayOperateTeacherAssignment(profile, token, profile.company_id, assignment))) throw new TRPCError({ code: "FORBIDDEN", message: "The selected teacher assignment does not match your authorised assessment scope." }); const assessment = await insert("sch_assessments", token, profile.company_id, { name: input.name, status: "Draft", amount: input.maxScore, notes: input.notes || null, data: { ...input, createdBy: profile.id, createdAt: now() } }); await audit(token, profile.company_id, profile, "Assessment created", "sch_assessments", assessment.id); return assessment; }
export async function recordSchoolAssessmentScores(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolScoreInput>) { const { profile, token } = await context(req, "teaching"); const assessment = await row("sch_assessments", token, profile.company_id, input.assessmentId); const assignment = await row("sch_teacher_assignments", token, profile.company_id, String(assessment.teacherAssignmentId)); if (!(await mayOperateTeacherAssignment(profile, token, profile.company_id, assignment))) throw new TRPCError({ code: "FORBIDDEN", message: "Only the assigned teacher or academic administrator may record these assessment scores." }); if (input.scores.some((line) => line.score > decimal(assessment.maxScore))) throw new TRPCError({ code: "BAD_REQUEST", message: "An assessment score cannot exceed the assessment maximum score." }); const enrolled = new Set((await rows("sch_enrollments", token, profile.company_id, 2_000)).filter((record) => record.classId === assessment.classId && record.status === "Active").map((record) => record.studentId)); if (input.scores.some((line) => !enrolled.has(line.studentId))) throw new TRPCError({ code: "FORBIDDEN", message: "Scores may only be entered for learners enrolled in the assessment class." }); const existing = await rows("sch_assessment_scores", token, profile.company_id, 2_000); for (const line of input.scores) { const prior = existing.find((record) => record.assessmentId === assessment.id && record.studentId === line.studentId); const data = { assessmentId: assessment.id, studentId: line.studentId, score: line.score, percentage: (line.score / decimal(assessment.maxScore)) * 100, remarks: line.remarks, enteredBy: profile.id, enteredAt: now() }; if (prior) await update("sch_assessment_scores", token, profile.company_id, prior.id, { amount: line.score, notes: line.remarks || null, data }); else await insert("sch_assessment_scores", token, profile.company_id, { name: `${assessment.name} · ${line.studentId}`, status: "Recorded", amount: line.score, notes: line.remarks || null, data }); }
  const finalized = await update("sch_assessments", token, profile.company_id, assessment.id, { status: "Scores recorded", data: { scoredAt: now(), scoredBy: profile.id, scoreCount: input.scores.length } }); await audit(token, profile.company_id, profile, "Assessment scores recorded", "sch_assessments", assessment.id); return finalized; }
export async function publishSchoolReportCard(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolReportCardInput>) { const { profile, token } = await context(req, "academic"); const [student, term, scale] = await Promise.all([row("sch_students", token, profile.company_id, input.studentId), row("sch_terms", token, profile.company_id, input.termId), row("sch_grading_scales", token, profile.company_id, input.gradingScaleId)]); if (scale.status !== "Active") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "A report card requires an active grading scale." }); const enrollment = (await rows("sch_enrollments", token, profile.company_id, 2_000)).find((record) => record.studentId === student.id && record.status === "Active"); if (!enrollment) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "An active enrollment is required before generating a report card." }); const assessments = (await rows("sch_assessments", token, profile.company_id, 2_000)).filter((record) => record.termId === term.id && record.classId === enrollment.classId && /scores recorded|published/i.test(record.status)); const allScores = await rows("sch_assessment_scores", token, profile.company_id, 5_000); const bands = Array.isArray(scale.bands) ? scale.bands : []; const results = assessments.map((assessment) => { const score = allScores.find((record) => record.assessmentId === assessment.id && record.studentId === student.id); return score ? { assessmentId: assessment.id, assessmentName: assessment.name, subjectId: assessment.subjectId, score: decimal(score.score), maxScore: decimal(assessment.maxScore), ...gradeFor(decimal(score.score), decimal(assessment.maxScore), bands) } : null; }).filter(Boolean); if (!results.length) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "At least one recorded assessment score is required before a report card can be generated." }); const average = results.reduce((sum, result) => sum + Number(result?.percentage || 0), 0) / results.length; const name = `${student.name} · ${term.name}`; const existing = (await rows("sch_report_cards", token, profile.company_id, 2_000)).find((record) => record.studentId === student.id && record.termId === term.id); const payload = { studentId: student.id, studentName: student.name, termId: term.id, termName: term.name, classId: enrollment.classId, gradingScaleId: scale.id, gradingScaleName: scale.name, results, average, ...gradeFor(average, 100, bands), generatedAt: now(), generatedBy: profile.id, publishedAt: input.publish ? now() : null };
  const report = existing ? await update("sch_report_cards", token, profile.company_id, existing.id, { status: input.publish ? "Published" : "Draft", notes: input.notes || null, data: payload }) : await insert("sch_report_cards", token, profile.company_id, { name, status: input.publish ? "Published" : "Draft", amount: average, notes: input.notes || null, data: payload }); await audit(token, profile.company_id, profile, input.publish ? "Report card published" : "Report card generated", "sch_report_cards", report.id); return report; }

export async function createSchoolAssignment(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAssignmentInput>) { const { profile, token } = await context(req, "teaching"); const assignment = await row("sch_teacher_assignments", token, profile.company_id, input.teacherAssignmentId); if (assignment.classId !== input.classId || assignment.subjectId !== input.subjectId || !(await mayOperateTeacherAssignment(profile, token, profile.company_id, assignment))) throw new TRPCError({ code: "FORBIDDEN", message: "The selected teacher assignment does not match your authorised assignment scope." }); const created = await insert("sch_assignments", token, profile.company_id, { name: input.name, status: "Published", amount: input.maximumScore, notes: input.instructions || null, data: { ...input, publishedBy: profile.id, publishedAt: now() } }); await audit(token, profile.company_id, profile, "Assignment published", "sch_assignments", created.id); return created; }
export async function submitSchoolAssignment(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAssignmentSubmissionInput>) { const { profile, token } = await context(req, "teaching"); const assignment = await row("sch_assignments", token, profile.company_id, input.assignmentId); const enrolled = (await rows("sch_enrollments", token, profile.company_id, 2_000)).some((record) => record.studentId === input.studentId && record.classId === assignment.classId && record.status === "Active"); if (!enrolled) throw new TRPCError({ code: "FORBIDDEN", message: "The selected learner is not enrolled in the assignment class." }); if (input.documentId) await row("sch_documents", token, profile.company_id, input.documentId); const existing = (await rows("sch_assignment_submissions", token, profile.company_id, 2_000)).find((record) => record.assignmentId === assignment.id && record.studentId === input.studentId); const payload = { assignmentId: assignment.id, studentId: input.studentId, documentId: input.documentId || null, submittedAt: now(), submittedBy: profile.id }; const submitted = existing ? await update("sch_assignment_submissions", token, profile.company_id, existing.id, { status: "Submitted", notes: input.notes || null, data: payload }) : await insert("sch_assignment_submissions", token, profile.company_id, { name: `${assignment.name} · ${input.studentId}`, status: "Submitted", notes: input.notes || null, data: payload }); await audit(token, profile.company_id, profile, "Assignment submission recorded", "sch_assignment_submissions", submitted.id); return submitted; }

export async function createSchoolFeeStructure(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolFeeStructureInput>) { const { profile, token } = await context(req, "finance"); await row("sch_terms", token, profile.company_id, input.termId); if (input.classId) await row("sch_classes", token, profile.company_id, input.classId); const fee = await insert("sch_fee_structures", token, profile.company_id, { name: input.name, status: "Active", amount: input.amount, notes: input.notes || null, data: { ...input, currency: "TZS", createdAt: now() } }); await audit(token, profile.company_id, profile, "Fee structure created", "sch_fee_structures", fee.id); return fee; }
export async function issueSchoolFeeInvoice(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolInvoiceInput>) { const { profile, token } = await context(req, "finance"); const [student, term] = await Promise.all([row("sch_students", token, profile.company_id, input.studentId), row("sch_terms", token, profile.company_id, input.termId)]); const fees = await Promise.all(input.feeStructureIds.map((id) => row("sch_fee_structures", token, profile.company_id, id))); if (fees.some((fee) => fee.termId !== term.id || fee.status !== "Active")) throw new TRPCError({ code: "BAD_REQUEST", message: "Invoices may only use active fee structures from the selected term." }); const total = fees.reduce((sum, fee) => sum + decimal(fee.amount), 0); const invoiceNo = `SCH-INV-${new Date().getUTCFullYear()}-${Date.now().toString().slice(-7)}`; const invoice = await insert("sch_fee_invoices", token, profile.company_id, { name: invoiceNo, status: "Open", amount: total, notes: input.notes || null, data: { invoiceNo, studentId: student.id, studentName: student.name, termId: term.id, termName: term.name, dueDate: input.dueDate, currency: "TZS", total, paidAmount: 0, balance: total, issuedAt: now() } }); for (const fee of fees) await insert("sch_fee_invoice_lines", token, profile.company_id, { name: `${invoiceNo} · ${fee.name}`, status: "Posted", amount: decimal(fee.amount), data: { invoiceId: invoice.id, feeStructureId: fee.id, feeName: fee.name, amount: decimal(fee.amount) } }); await audit(token, profile.company_id, profile, "Student fee invoice issued", "sch_fee_invoices", invoice.id); return invoice; }
export async function recordSchoolPayment(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolPaymentInput>) { const { profile, token } = await context(req, "finance"); const invoice = await row("sch_fee_invoices", token, profile.company_id, input.invoiceId); const paid = decimal(invoice.paidAmount); const balance = Math.max(0, decimal(invoice.balance ?? invoice.amount) || decimal(invoice.amount) - paid); if (input.amount > balance + 0.0001) throw new TRPCError({ code: "BAD_REQUEST", message: "The payment amount exceeds the remaining invoice balance." }); const receiptNo = `SCH-RCT-${Date.now().toString().slice(-8)}`; const payment = await insert("sch_payments", token, profile.company_id, { name: receiptNo, status: "Recorded", amount: input.amount, notes: input.notes || null, data: { receiptNo, invoiceId: invoice.id, invoiceNo: invoice.invoiceNo || invoice.name, studentId: invoice.studentId, method: input.method, reference: input.reference || null, currency: "TZS", paidAt: now(), financeReference: null } }); const nextPaid = paid + input.amount; const nextBalance = Math.max(0, decimal(invoice.amount) - nextPaid); const settled = await update("sch_fee_invoices", token, profile.company_id, invoice.id, { status: nextBalance === 0 ? "Paid" : "Partially paid", data: { paidAmount: nextPaid, balance: nextBalance, lastPaymentId: payment.id, settledAt: nextBalance === 0 ? now() : null } }); await audit(token, profile.company_id, profile, "Student fee payment recorded", "sch_payments", payment.id); return { payment, invoice: settled, balance: nextBalance }; }
export async function requestSchoolScholarship(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolScholarshipInput>) { const { profile, token } = await context(req, "finance"); const [student, term] = await Promise.all([row("sch_students", token, profile.company_id, input.studentId), row("sch_terms", token, profile.company_id, input.termId)]); const scholarship = await insert("sch_scholarships", token, profile.company_id, { name: `${student.name} · ${term.name}`, status: "Requested", amount: input.amount, notes: input.reason, data: { ...input, studentName: student.name, termName: term.name, requestedBy: profile.id, requestedAt: now() } }); const approval = await insert("sch_approval_requests", token, profile.company_id, { name: `Scholarship · ${student.name}`, status: "Pending", notes: input.reason, data: { requestType: "Scholarship", recordId: scholarship.id, requestedBy: profile.id, requestedAt: now() } }); await update("sch_scholarships", token, profile.company_id, scholarship.id, { data: { approvalId: approval.id } }); await audit(token, profile.company_id, profile, "Scholarship approval requested", "sch_scholarships", scholarship.id); return scholarship; }
export async function decideSchoolScholarship(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolScholarshipDecisionInput>) { const { profile, token } = await context(req, "governance"); const scholarship = await row("sch_scholarships", token, profile.company_id, input.scholarshipId); if (scholarship.status !== "Requested") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Only requested scholarships may be decided." }); const approval = (await rows("sch_approval_requests", token, profile.company_id, 2_000)).find((record) => record.recordId === scholarship.id && record.requestType === "Scholarship" && record.status === "Pending"); const decided = await update("sch_scholarships", token, profile.company_id, scholarship.id, { status: input.decision, data: { decidedBy: profile.id, decidedAt: now(), decisionNotes: input.notes } }); if (approval) await update("sch_approval_requests", token, profile.company_id, approval.id, { status: input.decision, notes: input.notes || null, data: { decidedBy: profile.id, decidedAt: now(), decisionNotes: input.notes } }); if (input.decision === "Approved") await notify(token, profile.company_id, "Scholarship approved", "Info", { scholarshipId: scholarship.id, studentId: scholarship.studentId, amount: scholarship.amount }); await audit(token, profile.company_id, profile, `Scholarship ${input.decision.toLowerCase()}`, "sch_scholarships", scholarship.id, input.notes); return decided; }

export async function createSchoolServiceRecord(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolServiceInput>) { const action = recordAction(input.table); const { profile, token } = await context(req, action); const record = await insert(input.table, token, profile.company_id, { name: input.name, status: "Active", amount: input.amount ?? null, notes: input.notes || null, data: { ...input.data, createdAt: now() } }); await audit(token, profile.company_id, profile, "School service record created", input.table, record.id); return record; }
export async function assignSchoolService(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolServiceAssignmentInput>) { const { profile, token } = await context(req, "services"); const serviceTable = input.table === "sch_transport_assignments" ? "sch_transport" : "sch_hostels"; const [student, service] = await Promise.all([row("sch_students", token, profile.company_id, input.studentId), row(serviceTable, token, profile.company_id, input.serviceId)]); if (input.termId) await row("sch_terms", token, profile.company_id, input.termId); const assignment = await insert(input.table, token, profile.company_id, { name: `${student.name} · ${service.name}`, status: "Active", notes: input.notes || null, data: { ...input, studentName: student.name, serviceName: service.name, assignedAt: now() } }); await audit(token, profile.company_id, profile, "School service assignment created", input.table, assignment.id); return assignment; }
export async function createSchoolLibraryLoan(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolLibraryLoanInput>) { const { profile, token } = await context(req, "services"); const [book, student] = await Promise.all([row("sch_books", token, profile.company_id, input.bookId), row("sch_students", token, profile.company_id, input.studentId)]); const available = decimal(book.availableCopies ?? book.available ?? book.copies); if (available < 1) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "This library item has no available copies to loan." }); const duplicate = (await rows("sch_library_loans", token, profile.company_id, 2_000)).find((record) => record.bookId === book.id && record.studentId === student.id && record.status === "On loan"); if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "This learner already has an open loan for the selected book." }); const loan = await insert("sch_library_loans", token, profile.company_id, { name: `${book.name} · ${student.name}`, status: "On loan", notes: input.notes || null, data: { bookId: book.id, bookName: book.name, studentId: student.id, studentName: student.name, dueDate: input.dueDate, issuedAt: now(), issuedBy: profile.id } }); await update("sch_books", token, profile.company_id, book.id, { data: { availableCopies: available - 1, available: available - 1 } }); await audit(token, profile.company_id, profile, "Library loan issued", "sch_library_loans", loan.id); return loan; }
export async function recordSchoolInventoryMovement(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolInventoryMovementInput>) { const { profile, token } = await context(req, "services"); const item = await row("sch_inventory_items", token, profile.company_id, input.itemId); const onHand = decimal(item.onHand ?? item.quantity); const next = onHand + input.quantityDelta; if (next < 0) throw new TRPCError({ code: "BAD_REQUEST", message: "This movement would make school inventory negative." }); const movement = await insert("sch_inventory_movements", token, profile.company_id, { name: `${input.quantityDelta > 0 ? "Receipt" : "Issue"} · ${item.name}`, status: "Posted", amount: Math.abs(input.quantityDelta) * decimal(item.unitCost ?? item.amount), notes: input.reason, data: { itemId: item.id, itemName: item.name, quantityDelta: input.quantityDelta, quantityAfter: next, reason: input.reason, postedAt: now() } }); await update("sch_inventory_items", token, profile.company_id, item.id, { amount: next * decimal(item.unitCost ?? item.amount), data: { onHand: next, lastMovementAt: now() } }); await audit(token, profile.company_id, profile, "School inventory movement posted", "sch_inventory_movements", movement.id, input.reason); return movement; }
export async function createSchoolDisciplineRecord(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolDisciplineInput>) { const { profile, token } = await context(req, "welfare"); const student = await row("sch_students", token, profile.company_id, input.studentId); const record = await insert("sch_disciplinary_records", token, profile.company_id, { name: `${input.category} · ${student.name}`, status: "Recorded", notes: input.description, data: { ...input, studentName: student.name, recordedBy: profile.id, recordedAt: now() } }); await audit(token, profile.company_id, profile, "Disciplinary record created", "sch_disciplinary_records", record.id); return record; }

export async function createSchoolAnnouncement(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolAnnouncementInput>) { const { profile, token } = await context(req, "communications"); if (input.audience === "Class" && !input.classId) throw new TRPCError({ code: "BAD_REQUEST", message: "A class audience requires a selected class." }); if (input.classId) await row("sch_classes", token, profile.company_id, input.classId); const announcement = await insert("sch_announcements", token, profile.company_id, { name: input.title, status: "Published", notes: input.body, data: { ...input, publishedAt: input.publishedAt || now(), publishedBy: profile.id } }); await audit(token, profile.company_id, profile, "School announcement published", "sch_announcements", announcement.id); return announcement; }
export async function sendSchoolMessage(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolMessageInput>) { const { profile, token } = await context(req, "communications"); if (input.recipientType === "Class" && !input.classId) throw new TRPCError({ code: "BAD_REQUEST", message: "A class message requires a selected class." }); const message = await insert("sch_messages", token, profile.company_id, { name: input.subject, status: "Sent", notes: input.body, data: { ...input, senderProfileId: profile.id, sentAt: now() } }); await audit(token, profile.company_id, profile, "School message sent", "sch_messages", message.id); return message; }
export async function linkSchoolPortal(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolPortalLinkInput>) { const { profile, token } = await context(req, "governance"); const targetTable = input.scope === "Teacher" ? "sch_teachers" : "sch_students"; await row(targetTable, token, profile.company_id, input.recordId); const duplicate = (await rows("sch_portal_links", token, profile.company_id, 2_000)).find((record) => record.profileId === input.profileId && record.scope === input.scope && record.recordId === input.recordId && record.status === "Active"); if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "This portal profile is already linked to the selected school record." }); const link = await insert("sch_portal_links", token, profile.company_id, { name: `${input.scope} portal link`, status: "Active", notes: input.notes || null, data: { ...input, linkedBy: profile.id, linkedAt: now() } }); await audit(token, profile.company_id, profile, "School portal link created", "sch_portal_links", link.id); return link; }
export async function createSchoolDocument(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolDocumentInput>) { const { profile, token } = await context(req, "admissions"); const ownerTable: Record<string, SchoolTable> = { Admission: "sch_admissions", Student: "sch_students", Guardian: "sch_guardians", Assignment: "sch_assignments", Discipline: "sch_disciplinary_records", "Report card": "sch_report_cards" }; await row(ownerTable[input.ownerType], token, profile.company_id, input.ownerId); const document = await insert("sch_documents", token, profile.company_id, { name: input.fileName, status: "Active", data: { ...input, uploadedBy: profile.id, uploadedAt: now() } }); await audit(token, profile.company_id, profile, "School document registered", "sch_documents", document.id); return document; }
export async function uploadSchoolDocument(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolDocumentUploadInput>) { const { profile, token } = await context(req, "admissions"); const ownerTable: Record<string, SchoolTable> = { Admission: "sch_admissions", Student: "sch_students", Guardian: "sch_guardians", Assignment: "sch_assignments", Discipline: "sch_disciplinary_records", "Report card": "sch_report_cards" }; await row(ownerTable[input.ownerType], token, profile.company_id, input.ownerId); const bytes = Buffer.from(input.base64, "base64"); if (!bytes.length || bytes.length > 6 * 1024 * 1024) throw new TRPCError({ code: "BAD_REQUEST", message: "School documents must be valid files no larger than 6 MB." }); const safeName = input.fileName.replace(/[^a-zA-Z0-9._-]/g, "_"); const stored = await storagePut(`school/${profile.company_id}/${input.ownerType.toLowerCase()}/${input.ownerId}/${safeName}`, bytes, input.mimeType); const document = await insert("sch_documents", token, profile.company_id, { name: input.fileName, status: "Active", data: { ownerType: input.ownerType, ownerId: input.ownerId, storageKey: stored.key, storageUrl: stored.url, fileName: input.fileName, mimeType: input.mimeType, access: input.access, uploadedBy: profile.id, uploadedAt: now() } }); await audit(token, profile.company_id, profile, "School document uploaded", "sch_documents", document.id); return document; }
export async function requestSchoolApproval(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolApprovalRequestInput>) { const { profile, token } = await context(req, "read"); const request = await insert("sch_approval_requests", token, profile.company_id, { name: input.subject, status: "Pending", notes: input.rationale, data: { ...input, requestedBy: profile.id, requestedAt: now() } }); await notify(token, profile.company_id, "School approval requires review", "Warning", { approvalId: request.id, requestType: input.requestType }); await audit(token, profile.company_id, profile, "School approval requested", "sch_approval_requests", request.id); return request; }
export async function decideSchoolApproval(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolApprovalDecisionInput>) { const { profile, token } = await context(req, "governance"); const request = await row("sch_approval_requests", token, profile.company_id, input.approvalId); if (request.status !== "Pending") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Only pending approval requests may be decided." }); const decided = await update("sch_approval_requests", token, profile.company_id, request.id, { status: input.decision, notes: input.decisionNotes || null, data: { decidedBy: profile.id, decidedAt: now(), decisionNotes: input.decisionNotes } }); await audit(token, profile.company_id, profile, `School approval ${input.decision.toLowerCase()}`, "sch_approval_requests", decided.id, input.decisionNotes); return decided; }
export async function markSchoolNotificationRead(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolIdInput>) { const { profile, token } = await context(req, "read"); return update("sch_notifications", token, profile.company_id, input.id, { status: "Read", data: { readAt: now(), readBy: profile.id } }); }
export async function listSchoolAudit(req: CreateExpressContextOptions["req"], input: z.infer<typeof schoolListInput>) { const { profile, token } = await context(req, "governance"); return searchable(await rows("sch_audit_logs", token, profile.company_id, input.limit), input.search); }

export async function getSchoolPortal(req: CreateExpressContextOptions["req"]) { const { profile, token, access } = await context(req, "portal"); const links = (await rows("sch_portal_links", token, profile.company_id, 500)).filter((link) => link.profileId === profile.id && link.status === "Active"); const studentIds = links.filter((link) => ["Parent", "Student"].includes(String(link.scope))).map((link) => String(link.recordId)); const teacherIds = links.filter((link) => link.scope === "Teacher").map((link) => String(link.recordId)); const [students, enrollments, attendance, invoices, reports, assignments, submissions, announcements, messages, teachers, teacherAssignments] = await Promise.all([rows("sch_students", token, profile.company_id, 500), rows("sch_enrollments", token, profile.company_id, 1_000), rows("sch_attendance_records", token, profile.company_id, 2_000), rows("sch_fee_invoices", token, profile.company_id, 1_000), rows("sch_report_cards", token, profile.company_id, 1_000), rows("sch_assignments", token, profile.company_id, 1_000), rows("sch_assignment_submissions", token, profile.company_id, 1_000), rows("sch_announcements", token, profile.company_id, 1_000), rows("sch_messages", token, profile.company_id, 1_000), rows("sch_teachers", token, profile.company_id, 500), rows("sch_teacher_assignments", token, profile.company_id, 1_000)]);
  if (access.canUsePortal && !links.length) return { access, links: [], students: [], teachers: [], enrollments: [], attendance: [], invoices: [], reports: [], assignments: [], submissions: [], announcements: [], messages: [] };
  const classIds = new Set(enrollments.filter((record) => studentIds.includes(String(record.studentId))).map((record) => String(record.classId))); return { access, links, students: students.filter((student) => studentIds.includes(student.id)), teachers: teachers.filter((teacher) => teacherIds.includes(teacher.id)), enrollments: enrollments.filter((record) => studentIds.includes(String(record.studentId))), attendance: attendance.filter((record) => studentIds.includes(String(record.studentId))), invoices: invoices.filter((record) => studentIds.includes(String(record.studentId))), reports: reports.filter((record) => studentIds.includes(String(record.studentId)) && record.status === "Published"), assignments: assignments.filter((record) => classIds.has(String(record.classId))), submissions: submissions.filter((record) => studentIds.includes(String(record.studentId))), announcements: announcements.filter((record) => record.audience === "All" || record.audience === "Students" || record.audience === "Parents" || (record.audience === "Class" && classIds.has(String(record.classId)))), messages: messages.filter((record) => record.recipientProfileId === profile.id || (record.recipientType === "Class" && classIds.has(String(record.classId))) || record.recipientType === "Parent" || record.recipientType === "Student"), teacherAssignments: teacherAssignments.filter((record) => teacherIds.includes(String(record.teacherId))) };
}

export async function getSchoolReports(req: CreateExpressContextOptions["req"]) { const { profile, token } = await context(req, "read"); const [students, admissions, enrollments, attendance, assessments, scores, invoices, payments, scholarships, libraryLoans, inventory, discipline, reports] = await Promise.all([rows("sch_students", token, profile.company_id), rows("sch_admissions", token, profile.company_id), rows("sch_enrollments", token, profile.company_id), rows("sch_attendance_records", token, profile.company_id, 5_000), rows("sch_assessments", token, profile.company_id), rows("sch_assessment_scores", token, profile.company_id, 5_000), rows("sch_fee_invoices", token, profile.company_id), rows("sch_payments", token, profile.company_id), rows("sch_scholarships", token, profile.company_id), rows("sch_library_loans", token, profile.company_id), rows("sch_inventory_items", token, profile.company_id), rows("sch_disciplinary_records", token, profile.company_id), rows("sch_report_cards", token, profile.company_id)]);
  const recordedAttendance = attendance.filter((record) => record.status === "Present" || record.status === "Late").length; const attendanceRate = attendance.length ? (recordedAttendance / attendance.length) * 100 : 0; const invoiceTotal = invoices.reduce((sum, invoice) => sum + decimal(invoice.amount), 0); const collected = payments.reduce((sum, payment) => sum + decimal(payment.amount), 0); const outstanding = invoices.reduce((sum, invoice) => sum + Math.max(0, decimal(invoice.balance ?? invoice.amount) || decimal(invoice.amount) - decimal(invoice.paidAmount)), 0); const averageScore = scores.length ? scores.reduce((sum, score) => sum + decimal(score.percentage), 0) / scores.length : 0; return { learners: { activeStudents: students.filter((record) => record.status === "Active").length, pendingAdmissions: admissions.filter((record) => record.status === "Submitted").length, activeEnrollments: enrollments.filter((record) => record.status === "Active").length, attendanceRate }, academics: { assessments: assessments.length, averageScore, publishedReportCards: reports.filter((record) => record.status === "Published").length }, finance: { invoiced: invoiceTotal, collected, outstanding, scholarshipsApproved: scholarships.filter((record) => record.status === "Approved").reduce((sum, record) => sum + decimal(record.amount), 0) }, services: { openLibraryLoans: libraryLoans.filter((record) => record.status === "On loan").length, inventoryValue: inventory.reduce((sum, item) => sum + decimal(item.amount), 0), disciplineCases: discipline.length } }; }
export async function getSchoolDashboard(req: CreateExpressContextOptions["req"]) { const { profile, token, access } = await dashboardContext(req); if (!access.canRead) return { access, totals: { activeStudents: 0, pendingAdmissions: 0, todayAttendanceRate: null, outstandingFees: 0, todayCollections: 0, publishedReportCards: 0, pendingApprovals: 0 }, notifications: [], announcements: [], pendingAdmissions: [] }; const [students, admissions, attendanceSessions, attendance, invoices, payments, reportCards, notifications, announcements, approvals] = await Promise.all([rows("sch_students", token, profile.company_id), rows("sch_admissions", token, profile.company_id), rows("sch_attendance_sessions", token, profile.company_id), rows("sch_attendance_records", token, profile.company_id, 5_000), rows("sch_fee_invoices", token, profile.company_id), rows("sch_payments", token, profile.company_id), rows("sch_report_cards", token, profile.company_id), rows("sch_notifications", token, profile.company_id), rows("sch_announcements", token, profile.company_id), rows("sch_approval_requests", token, profile.company_id)]);
  const today = new Date().toISOString().slice(0, 10); const todaySessions = attendanceSessions.filter((record) => record.attendanceDate === today); const todayAttendance = attendance.filter((record) => todaySessions.some((session) => session.id === record.sessionId)); const present = todayAttendance.filter((record) => ["Present", "Late"].includes(record.status)).length; const outstanding = invoices.reduce((sum, invoice) => sum + Math.max(0, decimal(invoice.balance ?? invoice.amount) || decimal(invoice.amount) - decimal(invoice.paidAmount)), 0); return { access, totals: { activeStudents: students.filter((record) => record.status === "Active").length, pendingAdmissions: admissions.filter((record) => ["Submitted", "Waitlisted"].includes(record.status)).length, todayAttendanceRate: todayAttendance.length ? (present / todayAttendance.length) * 100 : null, outstandingFees: outstanding, todayCollections: payments.filter((record) => String(record.paidAt || "").slice(0, 10) === today).reduce((sum, record) => sum + decimal(record.amount), 0), publishedReportCards: reportCards.filter((record) => record.status === "Published").length, pendingApprovals: approvals.filter((record) => record.status === "Pending").length }, notifications: notifications.filter((record) => record.status !== "Read").slice(0, 20), announcements: announcements.filter((record) => record.status === "Published").slice(0, 10), pendingAdmissions: admissions.filter((record) => ["Submitted", "Waitlisted"].includes(record.status)).slice(0, 20) }; }
