-- Unify sales_subscriptions and tenant_subscriptions for Global Admin.
-- tenant_subscriptions is the entitlement source; sales_subscriptions is the billing source.
create or replace function public.platform_admin_control_snapshot()
returns jsonb language plpgsql security definer set search_path = public, auth, pg_temp as $$
declare v_subscriptions jsonb; v_support jsonb; v_invitations jsonb; v_tenants jsonb;
begin
  if auth.uid() is null or not public.billing_is_platform_admin() then raise exception 'platform administrator access required' using errcode='42501'; end if;
  with logged as (select p.company_id, max(u.last_sign_in_at) last_sign_in_at, count(*)::int user_count, count(*) filter (where p.is_active)::int active_user_count from public.profiles p join auth.users u on u.id=p.id where u.last_sign_in_at is not null group by p.company_id), unified as (
    select s.id, 'sales'::text source, s.company_id, c.name company_name, s.name, s.plan, s.cycle, s.status, case when lower(coalesce(s.status,'')) in ('cancelled','canceled','expired') then 'Cancelled' when s.next_billing_date is not null and s.next_billing_date < now() then 'Expired' when s.next_billing_date is null then 'No expiry date' else 'Active' end access_status, s.amount, 'TZS'::text currency, s.start_date started_at, s.next_billing_date expires_at, s.next_billing_date, max(l.last_sign_in_at) last_sign_in_at, (lower(coalesce(s.status,'')) in ('cancelled','canceled','expired') or (s.next_billing_date is not null and s.next_billing_date < now())) is_expired
    from public.sales_subscriptions s join public.companies c on c.id=s.company_id join logged l on l.company_id=s.company_id group by s.id,c.name,l.last_sign_in_at
    union all
    select ts.id, 'tenant'::text, ts.company_id, c.name, coalesce(bp.name,bp.code,'Tenant subscription'), coalesce(bp.name,bp.code,'Tenant plan'), ts.billing_cycle, ts.status, case when lower(coalesce(ts.status,'')) in ('cancelled','canceled','expired') then 'Cancelled' when coalesce(ts.expires_at,ts.grace_expires_at) is not null and coalesce(ts.expires_at,ts.grace_expires_at) < now() then 'Expired' when coalesce(ts.expires_at,ts.grace_expires_at) is null then 'No expiry date' else 'Active' end, ts.amount, ts.currency, ts.started_at, coalesce(ts.expires_at,ts.grace_expires_at), coalesce(ts.expires_at,ts.grace_expires_at), l.last_sign_in_at, (lower(coalesce(ts.status,'')) in ('cancelled','canceled','expired') or (ts.expires_at is not null and ts.expires_at < now()))
    from public.tenant_subscriptions ts join public.companies c on c.id=ts.company_id left join public.billing_plans bp on bp.id=ts.plan_id join logged l on l.company_id=ts.company_id
  ) select coalesce(jsonb_agg(to_jsonb(x) order by x.last_sign_in_at desc nulls last,x.company_name,x.name),'[]'::jsonb) into v_subscriptions from (select * from unified order by last_sign_in_at desc nulls last limit 300) x;
  with logged as (select p.company_id, max(u.last_sign_in_at) last_sign_in_at, count(*)::int user_count, count(*) filter (where p.is_active)::int active_user_count from public.profiles p join auth.users u on u.id=p.id where u.last_sign_in_at is not null group by p.company_id), unified as (
    select s.id,'sales' source,s.company_id,c.name company_name,s.status,s.next_billing_date expires_at,s.next_billing_date,max(l.last_sign_in_at) last_sign_in_at,(lower(coalesce(s.status,'')) in ('cancelled','canceled','expired') or (s.next_billing_date is not null and s.next_billing_date < now())) is_expired from public.sales_subscriptions s join public.companies c on c.id=s.company_id join logged l on l.company_id=s.company_id group by s.id,c.name,l.last_sign_in_at
    union all select ts.id,'tenant',ts.company_id,c.name,ts.status,coalesce(ts.expires_at,ts.grace_expires_at),coalesce(ts.expires_at,ts.grace_expires_at),l.last_sign_in_at,(lower(coalesce(ts.status,'')) in ('cancelled','canceled','expired') or (ts.expires_at is not null and ts.expires_at < now())) from public.tenant_subscriptions ts join public.companies c on c.id=ts.company_id join logged l on l.company_id=ts.company_id
  ) select coalesce(jsonb_agg(to_jsonb(x) order by x.last_sign_in_at desc nulls last,x.company_name),'[]'::jsonb) into v_tenants from (select c.id,c.name company_name,c.category,c.country,c.currency,l.user_count,l.active_user_count,l.last_sign_in_at,count(u.id)::int subscription_count,count(u.id) filter(where not u.is_expired)::int current_subscription_count,count(u.id) filter(where u.is_expired)::int expired_subscription_count,case when count(u.id)=0 then 'No subscription' when count(u.id) filter(where not u.is_expired)>0 then 'Active' else 'Expired' end billing_status,max(u.expires_at) latest_expires_at from public.companies c join logged l on l.company_id=c.id left join unified u on u.company_id=c.id group by c.id,c.name,c.category,c.country,c.currency,l.user_count,l.active_user_count,l.last_sign_in_at order by l.last_sign_in_at desc nulls last limit 100) x;
  select coalesce(jsonb_agg(to_jsonb(t) order by t.updated_at desc),'[]'::jsonb) into v_support from (select id,company_id,subject,category,priority,status,customer,created_at,updated_at from public.support_tickets order by updated_at desc limit 100)t;
  select coalesce(jsonb_agg(to_jsonb(i) order by i.created_at desc),'[]'::jsonb) into v_invitations from (select id,company_id,email,full_name,role,status,expires_at,created_at,updated_at from public.team_invitations order by created_at desc limit 100)i;
  return jsonb_build_object('tenants',v_tenants,'subscriptions',v_subscriptions,'support',v_support,'invitations',v_invitations,'generatedAt',now());
end; $$;

create or replace function public.platform_admin_control_action(p_action text,p_target_id uuid default null,p_reason text default null,p_company_id uuid default null,p_plan text default null,p_name text default null,p_cycle text default null,p_amount numeric default null,p_status text default null,p_extension_days integer default null,p_subscription_source text default 'sales')
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_action text:=upper(btrim(coalesce(p_action,''))); v_reason text:=btrim(coalesce(p_reason,'')); v_source text:=lower(coalesce(p_subscription_source,'sales')); v_actor_role text; v_sub public.sales_subscriptions%rowtype; v_tsub public.tenant_subscriptions%rowtype; v_old_status text; v_new_status text; v_old_plan text; v_new_plan text; v_new_id uuid; v_audit_id uuid; v_plan_id uuid;
begin
 if auth.uid() is null or not public.billing_is_platform_admin() then raise exception 'platform administrator access required' using errcode='42501'; end if; if v_reason='' or char_length(v_reason)>1000 then raise exception 'a concise reason is required' using errcode='22023'; end if; if v_action not in('CREATE_SUBSCRIPTION','UPDATE_SUBSCRIPTION','CANCEL_SUBSCRIPTION','RESUME_SUBSCRIPTION','EXTEND_SUBSCRIPTION','CHANGE_PLAN','APPROVE_SUPPORT_TICKET','REJECT_SUPPORT_TICKET','REVOKE_INVITATION','ACTIVATE_USER','DEACTIVATE_USER') then raise exception 'unsupported platform control action' using errcode='22023'; end if; select role into v_actor_role from public.profiles where id=auth.uid();
 if v_action='CREATE_SUBSCRIPTION' then if p_company_id is null or nullif(btrim(coalesce(p_plan,'')),'') is null then raise exception 'company and plan are required' using errcode='22023'; end if; insert into public.sales_subscriptions(company_id,name,plan,cycle,status,amount,start_date,next_billing_date,notes) values(p_company_id,coalesce(nullif(btrim(p_name),''),p_plan),btrim(p_plan),coalesce(nullif(btrim(p_cycle),''),'Monthly'),coalesce(nullif(btrim(p_status),''),'Active'),p_amount,now(),case when p_extension_days is not null then now()+make_interval(days=>p_extension_days) else null end,v_reason) returning id into v_new_id; insert into public.subscription_events(company_id,subscription_id,event_type,previous_status,new_status,actor_profile_id,actor_type,details) values(p_company_id,null,'PLATFORM_ADMIN_SUBSCRIPTION_CREATED',null,coalesce(nullif(btrim(p_status),''),'Active'),auth.uid(),'platform_admin',jsonb_build_object('reason',v_reason,'salesSubscriptionId',v_new_id,'plan',p_plan));
 elsif v_action in('ACTIVATE_USER','DEACTIVATE_USER') then if p_target_id is null then raise exception 'target is required' using errcode='22023'; end if; update public.profiles set is_active=(v_action='ACTIVATE_USER'),updated_at=now() where id=p_target_id; if not found then raise exception 'user profile not found' using errcode='P0002'; end if;
 elsif v_action in('APPROVE_SUPPORT_TICKET','REJECT_SUPPORT_TICKET') then if p_target_id is null then raise exception 'target is required' using errcode='22023'; end if; update public.support_tickets set status=case when v_action='APPROVE_SUPPORT_TICKET' then 'in_progress' else 'rejected' end,updated_at=now() where id=p_target_id; if not found then raise exception 'support ticket not found' using errcode='P0002'; end if;
 elsif v_action='REVOKE_INVITATION' then if p_target_id is null then raise exception 'target is required' using errcode='22023'; end if; update public.team_invitations set status='revoked',revoked_at=now(),updated_at=now() where id=p_target_id; if not found then raise exception 'invitation not found' using errcode='P0002'; end if;
 elsif v_source='tenant' then select * into v_tsub from public.tenant_subscriptions where id=p_target_id for update; if not found then raise exception 'tenant subscription not found' using errcode='P0002'; end if; v_old_status:=v_tsub.status; select coalesce(bp.name,bp.code) into v_old_plan from public.billing_plans bp where bp.id=v_tsub.plan_id; v_new_status:=v_old_status; v_new_plan:=v_old_plan; if v_action='CHANGE_PLAN' then select id into v_plan_id from public.billing_plans where lower(name)=lower(btrim(p_plan)) or lower(code)=lower(btrim(p_plan)) order by created_at desc limit 1; if v_plan_id is null then raise exception 'billing plan not found' using errcode='P0002'; end if; v_new_plan:=btrim(p_plan); elsif v_action='CANCEL_SUBSCRIPTION' then v_new_status:='Cancelled'; elsif v_action='RESUME_SUBSCRIPTION' then v_new_status:='Active'; elsif v_action='EXTEND_SUBSCRIPTION' then if p_extension_days not in(7,15,30,60,90) then raise exception 'extension must be 7, 15, 30, 60, or 90 days' using errcode='22023'; end if; v_new_status:='Active'; end if; update public.tenant_subscriptions set plan_id=coalesce(v_plan_id,plan_id),status=v_new_status,cancelled_at=case when v_action='CANCEL_SUBSCRIPTION' then now() when v_action='RESUME_SUBSCRIPTION' then null else cancelled_at end,expires_at=case when v_action='EXTEND_SUBSCRIPTION' then greatest(coalesce(expires_at,now()),now())+make_interval(days=>p_extension_days) when v_action='RESUME_SUBSCRIPTION' and (expires_at is null or expires_at<now()) then now()+interval '30 days' else expires_at end,updated_at=now() where id=p_target_id; insert into public.subscription_events(company_id,subscription_id,event_type,previous_status,new_status,actor_profile_id,actor_type,details) values(v_tsub.company_id,null,v_action,v_old_status,v_new_status,auth.uid(),'platform_admin',jsonb_build_object('reason',v_reason,'tenantSubscriptionId',v_tsub.id,'previousPlan',v_old_plan,'newPlan',v_new_plan,'extensionDays',p_extension_days));
 else select * into v_sub from public.sales_subscriptions where id=p_target_id for update; if not found then raise exception 'sales subscription not found' using errcode='P0002'; end if; v_old_status:=v_sub.status; v_old_plan:=v_sub.plan; v_new_status:=v_old_status; v_new_plan:=v_old_plan; if v_action='CANCEL_SUBSCRIPTION' then v_new_status:='cancelled'; elsif v_action='RESUME_SUBSCRIPTION' then v_new_status:='Active'; elsif v_action='CHANGE_PLAN' then if nullif(btrim(coalesce(p_plan,'')),'') is null then raise exception 'plan is required' using errcode='22023'; end if; v_new_plan:=btrim(p_plan); elsif v_action='EXTEND_SUBSCRIPTION' then if p_extension_days not in(7,15,30,60,90) then raise exception 'extension must be 7,15,30,60,90' using errcode='22023'; end if; v_new_status:='Active'; end if; update public.sales_subscriptions set status=v_new_status,plan=v_new_plan,next_billing_date=case when v_action='EXTEND_SUBSCRIPTION' then greatest(coalesce(next_billing_date,now()),now())+make_interval(days=>p_extension_days) when v_action='RESUME_SUBSCRIPTION' and (next_billing_date is null or next_billing_date<now()) then now()+interval '30 days' else next_billing_date end,updated_at=now() where id=p_target_id; insert into public.subscription_events(company_id,subscription_id,event_type,previous_status,new_status,actor_profile_id,actor_type,details) values(v_sub.company_id,null,v_action,v_old_status,v_new_status,auth.uid(),'platform_admin',jsonb_build_object('reason',v_reason,'salesSubscriptionId',v_sub.id,'previousPlan',v_old_plan,'newPlan',v_new_plan,'extensionDays',p_extension_days)); end if;
 insert into public.platform_admin_actions(actor_user_id,actor_role,action,target_type,target_id,reason,confirmation_text,details) values(auth.uid(),coalesce(v_actor_role,'platform administrator'),v_action,case when v_action like '%SUBSCRIPTION' or v_action='CHANGE_PLAN' then 'subscription' when v_action like '%TICKET' then 'support_ticket' when v_action='REVOKE_INVITATION' then 'invitation' else 'profile' end,coalesce(p_target_id::text,v_new_id::text),v_reason,'CONFIRM:'||v_action||':'||coalesce(p_target_id::text,v_new_id::text),jsonb_build_object('status',p_status,'plan',p_plan,'companyId',p_company_id,'subscriptionSource',v_source)); return jsonb_build_object('action',v_action,'targetId',coalesce(p_target_id,v_new_id),'auditId',v_audit_id); end; $$;
revoke all on function public.platform_admin_control_snapshot() from public,anon,authenticated; grant execute on function public.platform_admin_control_snapshot() to authenticated;
revoke all on function public.platform_admin_control_action(text,uuid,text,uuid,text,text,text,numeric,text,integer,text) from public,anon,authenticated; grant execute on function public.platform_admin_control_action(text,uuid,text,uuid,text,text,text,numeric,text,integer,text) to authenticated;
