-- Fix reconciliation snapshot ordering contract for Money Agent.
BEGIN;
CREATE OR REPLACE FUNCTION public.money_agent_snapshot(p_limit integer DEFAULT 100)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth AS $$
DECLARE c uuid:=public.current_company_id(); l integer:=greatest(1,least(coalesce(p_limit,100),200)); v_agent_restricted boolean:=public.money_agent_has_role(ARRAY['money agent','agent','teller','cashier']);
BEGIN
  PERFORM public.money_agent_require('view');
  RETURN jsonb_build_object(
    'companyId',c,
    'currency','TZS',
    'timezone','Africa/Dar_es_Salaam',
    'permissions',jsonb_build_object('canOperate',public.money_agent_can_operate(),'canManage',public.money_agent_can_manage(),'canApprove',public.money_agent_can_approve(),'canAudit',public.money_agent_can_audit()),
    'metrics',jsonb_build_object(
      'agentCount',(SELECT count(*) FROM public.money_agent_agents a WHERE a.company_id=c AND (NOT v_agent_restricted OR a.profile_id=auth.uid())),
      'activeAgentCount',(SELECT count(*) FROM public.money_agent_agents a WHERE a.company_id=c AND a.status='Active' AND (NOT v_agent_restricted OR a.profile_id=auth.uid())),
      'customerCount',(SELECT count(*) FROM public.money_agent_customers cu WHERE cu.company_id=c AND cu.status='Active' AND (NOT v_agent_restricted OR cu.created_by=auth.uid() OR EXISTS (SELECT 1 FROM public.money_agent_transactions t JOIN public.money_agent_agents a ON a.id=t.agent_id WHERE t.company_id=c AND t.customer_id=cu.id AND a.profile_id=auth.uid()))),
      'floatBalance',coalesce((SELECT sum(available_balance) FROM public.money_agent_wallets w WHERE w.company_id=c AND w.owner_type='Agent' AND w.wallet_type='Float' AND w.status='Active' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=w.owner_id AND a.profile_id=auth.uid()))),0),
      'cashBalance',coalesce((SELECT sum(available_balance) FROM public.money_agent_wallets w WHERE w.company_id=c AND w.owner_type='Agent' AND w.wallet_type='Cash' AND w.status='Active' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=w.owner_id AND a.profile_id=auth.uid()))),0),
      'commissionBalance',coalesce((SELECT sum(available_balance) FROM public.money_agent_wallets w WHERE w.company_id=c AND w.owner_type='Agent' AND w.wallet_type='Commission' AND w.status='Active' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=w.owner_id AND a.profile_id=auth.uid()))),0),
      'todayTransactions',(SELECT count(*) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.requested_at::date=(now() AT TIME ZONE 'Africa/Dar_es_Salaam')::date AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),
      'pendingTransactions',(SELECT count(*) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.status IN ('Awaiting Authorization','Processing','Pending Provider') AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),
      'successfulTransactions',(SELECT count(*) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.status='Successful' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),
      'failedTransactions',(SELECT count(*) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.status='Failed' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),
      'cashInAmount',coalesce((SELECT sum(t.amount) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.transaction_type='Cash In' AND t.status='Successful' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),0),
      'cashOutAmount',coalesce((SELECT sum(t.amount) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.transaction_type='Cash Out' AND t.status='Successful' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),0),
      'feeRevenue',coalesce((SELECT sum(t.fee) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.status='Successful' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),0),
      'commissionAccrued',coalesce((SELECT sum(t.commission) FROM public.money_agent_transactions t WHERE t.company_id=c AND t.status='Successful' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid()))),0),
      'openRiskEvents',(SELECT count(*) FROM public.money_agent_risk_events r WHERE r.company_id=c AND r.status NOT IN ('Cleared','Confirmed') AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=r.agent_id AND a.profile_id=auth.uid()))),
      'openAlerts',(SELECT count(*) FROM public.money_agent_alerts r WHERE r.company_id=c AND r.status='Open' AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=r.agent_id AND a.profile_id=auth.uid())))
    ),
    'branches',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.name) FROM (SELECT id,branch_code AS "branchCode",name,region,district,ward,address,phone,status FROM public.money_agent_branches b WHERE b.company_id=c AND (NOT v_agent_restricted OR b.id IN (SELECT a.branch_id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) LIMIT 200)x),'[]'::jsonb),
    'agents',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT a.id,a.agent_code AS "agentCode",a.full_name AS "fullName",a.phone,a.national_id AS "nationalId",a.branch_id AS "branchId",a.supervisor_id AS "supervisorId",a.kyc_status AS "kycStatus",a.kyb_status AS "kybStatus",a.status,a.daily_limit AS "dailyLimit",a.monthly_limit AS "monthlyLimit",coalesce((SELECT pc.status FROM public.money_agent_pin_credentials pc WHERE pc.company_id=c AND pc.agent_id=a.id LIMIT 1),'Not configured') AS "pinStatus",a.created_at AS "createdAt" FROM public.money_agent_agents a WHERE a.company_id=c AND (NOT v_agent_restricted OR a.profile_id=auth.uid()) ORDER BY a.created_at DESC LIMIT 200)x),'[]'::jsonb),
    'customers',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT id,full_name AS "fullName",phone,national_id AS "nationalId",kyc_status AS "kycStatus",status,created_at AS "createdAt" FROM public.money_agent_customers cu WHERE cu.company_id=c AND (NOT v_agent_restricted OR cu.created_by=auth.uid() OR EXISTS (SELECT 1 FROM public.money_agent_transactions t JOIN public.money_agent_agents a ON a.id=t.agent_id WHERE t.company_id=c AND t.customer_id=cu.id AND a.profile_id=auth.uid())) ORDER BY created_at DESC LIMIT 500)x),'[]'::jsonb),
    'wallets',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."ownerType",x."walletType") FROM (SELECT id,owner_type AS "ownerType",owner_id AS "ownerId",wallet_type AS "walletType",currency,available_balance AS "availableBalance",status FROM public.money_agent_wallets w WHERE w.company_id=c AND (NOT v_agent_restricted OR (w.owner_type='Agent' AND EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=w.owner_id AND a.profile_id=auth.uid()))) ORDER BY owner_type,wallet_type LIMIT 500)x),'[]'::jsonb),
    'services',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.name) FROM (SELECT id,service_code AS "serviceCode",name,service_type AS "serviceType",provider_code AS "providerCode",requires_provider AS "requiresProvider",active FROM public.money_agent_services WHERE company_id=c ORDER BY name LIMIT 200)x),'[]'::jsonb),
    'feeRules',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."serviceCode",x."minAmount") FROM (SELECT id,service_code AS "serviceCode",min_amount AS "minAmount",max_amount AS "maxAmount",fee_type AS "feeType",fee_value AS "feeValue",active FROM public.money_agent_fee_rules WHERE company_id=c ORDER BY service_code,min_amount LIMIT 200)x),'[]'::jsonb),
    'commissionRules',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."serviceCode") FROM (SELECT id,service_code AS "serviceCode",commission_type AS "commissionType",commission_value AS "commissionValue",active FROM public.money_agent_commission_rules WHERE company_id=c ORDER BY service_code LIMIT 200)x),'[]'::jsonb),
    'limits',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."transactionType") FROM (SELECT id,agent_id AS "agentId",transaction_type AS "transactionType",max_single_amount AS "maxSingleAmount",daily_amount AS "dailyAmount",monthly_amount AS "monthlyAmount",velocity_window_minutes AS "velocityWindowMinutes",velocity_count AS "velocityCount",active FROM public.money_agent_limits lim WHERE lim.company_id=c AND (NOT v_agent_restricted OR lim.agent_id IS NULL OR lim.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY transaction_type LIMIT 500)x),'[]'::jsonb),
    'transactions',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."requestedAt" DESC) FROM (SELECT id,transaction_ref AS "transactionRef",idempotency_key AS "idempotencyKey",agent_id AS "agentId",branch_id AS "branchId",customer_id AS "customerId",service_id AS "serviceId",transaction_type AS "transactionType",amount,fee,commission,currency,status,authorization_method AS "authorizationMethod",provider_code AS "providerCode",provider_reference AS "providerReference",failure_reason AS "failureReason",requested_at AS "requestedAt",completed_at AS "completedAt",created_at AS "createdAt" FROM public.money_agent_transactions t WHERE t.company_id=c AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid())) ORDER BY requested_at DESC LIMIT 500)x),'[]'::jsonb),
    'approvals',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."requestedAt" DESC) FROM (SELECT id,transaction_id AS "transactionId",status,requested_by AS "requestedBy",decided_by AS "decidedBy",note,requested_at AS "requestedAt",decided_at AS "decidedAt" FROM public.money_agent_approvals ap WHERE ap.company_id=c AND (NOT v_agent_restricted OR EXISTS (SELECT 1 FROM public.money_agent_transactions t JOIN public.money_agent_agents a ON a.id=t.agent_id WHERE t.company_id=c AND t.id=ap.transaction_id AND a.profile_id=auth.uid())) ORDER BY requested_at DESC LIMIT 200)x),'[]'::jsonb),
    'settlements',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."businessDate" DESC) FROM (SELECT id,agent_id AS "agentId",branch_id AS "branchId",business_date AS "businessDate",opening_float AS "openingFloat",closing_float AS "closingFloat",expected_float AS "expectedFloat",variance,status,notes FROM public.money_agent_settlements s WHERE s.company_id=c AND (NOT v_agent_restricted OR s.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY business_date DESC LIMIT 200)x),'[]'::jsonb),
    'reconciliations',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT r.id,r.settlement_id AS "settlementId",r.status,r.expected_amount AS "expectedAmount",r.actual_amount AS "actualAmount",r.variance,r.notes,r.created_at AS "createdAt" FROM public.money_agent_reconciliations r JOIN public.money_agent_settlements s ON s.id=r.settlement_id WHERE r.company_id=c AND (NOT v_agent_restricted OR s.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY r.created_at DESC LIMIT 200)x),'[]'::jsonb),
    'alerts',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT al.id,al.agent_id AS "agentId",al.alert_type AS "alertType",al.severity,al.title,al.body,al.status,al.created_at AS "createdAt" FROM public.money_agent_alerts al WHERE al.company_id=c AND al.status<>'Resolved' AND (NOT v_agent_restricted OR al.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY al.created_at DESC LIMIT 200)x),'[]'::jsonb),
    'receipts',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."issuedAt" DESC) FROM (SELECT rc.id,rc.transaction_id AS "transactionId",rc.receipt_number AS "receiptNumber",rc.channel,rc.recipient_phone AS "recipientPhone",rc.issued_at AS "issuedAt" FROM public.money_agent_receipts rc JOIN public.money_agent_transactions t ON t.id=rc.transaction_id WHERE rc.company_id=c AND (NOT v_agent_restricted OR t.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY rc.issued_at DESC LIMIT 200)x),'[]'::jsonb),
    'notifications',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT n.id,n.transaction_id AS "transactionId",n.agent_id AS "agentId",n.channel,n.status,n.title,n.body,n.created_at AS "createdAt" FROM public.money_agent_notifications n WHERE n.company_id=c AND (NOT v_agent_restricted OR n.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY n.created_at DESC LIMIT 200)x),'[]'::jsonb),
    'riskEvents',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT r.id,r.agent_id AS "agentId",r.transaction_id AS "transactionId",r.risk_type AS "riskType",r.severity,r.status,r.score,r.reason,r.created_at AS "createdAt" FROM public.money_agent_risk_events r WHERE r.company_id=c AND r.status NOT IN ('Cleared','Confirmed') AND (NOT v_agent_restricted OR r.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY r.created_at DESC LIMIT 200)x),'[]'::jsonb),
    'dailySummaries',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."businessDate" DESC) FROM (SELECT ds.id,ds.agent_id AS "agentId",ds.branch_id AS "branchId",ds.business_date AS "businessDate",ds.transaction_count AS "transactionCount",ds.successful_count AS "successfulCount",ds.failed_count AS "failedCount",ds.cash_in_amount AS "cashInAmount",ds.cash_out_amount AS "cashOutAmount",ds.fee_amount AS "feeAmount",ds.commission_amount AS "commissionAmount" FROM public.money_agent_daily_summaries ds WHERE ds.company_id=c AND (NOT v_agent_restricted OR ds.agent_id IN (SELECT a.id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) ORDER BY ds.business_date DESC LIMIT 200)x),'[]'::jsonb),
    'agentPerformance',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."successfulAmount" DESC) FROM (SELECT a.id,a.agent_code AS "agentCode",a.full_name AS "fullName",a.branch_id AS "branchId",count(t.id) FILTER (WHERE t.status='Successful') AS "successfulCount",coalesce(sum(t.amount) FILTER (WHERE t.status='Successful'),0) AS "successfulAmount",coalesce(sum(t.fee) FILTER (WHERE t.status='Successful'),0) AS "feeAmount",coalesce(sum(t.commission) FILTER (WHERE t.status='Successful'),0) AS "commissionAmount" FROM public.money_agent_agents a LEFT JOIN public.money_agent_transactions t ON t.agent_id=a.id AND t.company_id=c WHERE a.company_id=c AND (NOT v_agent_restricted OR a.profile_id=auth.uid()) GROUP BY a.id,a.agent_code,a.full_name,a.branch_id LIMIT 200)x),'[]'::jsonb),
    'branchPerformance',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."transactionAmount" DESC) FROM (SELECT b.id,b.branch_code AS "branchCode",b.name,count(t.id) FILTER (WHERE t.status='Successful') AS "successfulCount",coalesce(sum(t.amount) FILTER (WHERE t.status='Successful'),0) AS "transactionAmount",coalesce(sum(t.fee) FILTER (WHERE t.status='Successful'),0) AS "feeAmount" FROM public.money_agent_branches b LEFT JOIN public.money_agent_transactions t ON t.branch_id=b.id AND t.company_id=c WHERE b.company_id=c AND (NOT v_agent_restricted OR b.id IN (SELECT a.branch_id FROM public.money_agent_agents a WHERE a.company_id=c AND a.profile_id=auth.uid())) GROUP BY b.id,b.branch_code,b.name LIMIT 200)x),'[]'::jsonb),
    'customerActivity',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."transactionCount" DESC) FROM (SELECT cu.id,cu.full_name AS "fullName",cu.phone,count(t.id) AS "transactionCount",coalesce(sum(t.amount) FILTER (WHERE t.status='Successful'),0) AS "successfulAmount" FROM public.money_agent_customers cu LEFT JOIN public.money_agent_transactions t ON t.customer_id=cu.id AND t.company_id=c WHERE cu.company_id=c AND (NOT v_agent_restricted OR cu.created_by=auth.uid() OR EXISTS (SELECT 1 FROM public.money_agent_agents a WHERE a.company_id=c AND a.id=t.agent_id AND a.profile_id=auth.uid())) GROUP BY cu.id,cu.full_name,cu.phone LIMIT 500)x),'[]'::jsonb),
    'auditEvents',CASE WHEN public.money_agent_can_audit() THEN coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x."createdAt" DESC) FROM (SELECT id,actor_profile_id AS "actorProfileId",action,entity_type AS "entityType",entity_id AS "entityId",metadata,created_at AS "createdAt" FROM public.money_agent_audit_events WHERE company_id=c ORDER BY created_at DESC LIMIT 200)x),'[]'::jsonb) ELSE '[]'::jsonb END
  );
END; $$;
COMMIT;
