// The API-only bundle is generated by the Vercel build and has no source declaration.
// @ts-ignore generated server bundle has no checked-in declaration
import { createApiApp } from "../dist/api.js";

export default createApiApp();
